# w-style module: motion (user-scope) — timing/easing profile rendered for both
# Hyprland (animations.lua, in deciseconds) and Quickshell (motion.json,
# milliseconds) so transitions stay in sync. Source is the active theme's
# motion.conf, falling back to baseline `w` when omitted. Both files written
# in-place; Hyprland is reloaded, Quickshell's Motion.qml singleton picks up
# motion.json via FileView. Band 100 = compositor + shell surfaces.
DESC="motion timing/easing (Hyprland + Quickshell)"

HYPR_ANIM_REL=".config/hypr/animations.lua"
QS_MOTION_REL=".config/quickshell/w/core/motion.json"

# Hyprland animation speed is in deciseconds; motion tokens are milliseconds.
# %g keeps integers clean (300→3) and allows decimals (180→1.8).
ms_to_ds() { awk "BEGIN{printf \"%g\", $1/100}"; }

# W_MOTION_BEZIER is 4 comma-separated numbers (x0,y0,x1,y1); hl.curve wants two
# control points as { {x0, y0}, {x1, y1} }. Emit that literal from the 4 values.
bezier_points() { awk -F', *' '{printf "{ {%s, %s}, {%s, %s} }", $1, $2, $3, $4}' <<<"$W_MOTION_BEZIER"; }

render_user() {
  load_motion "$(resolve_theme_file "$(w_userscope_theme_dir)" motion.conf)"
  # Hub -> Appearance -> Settings -> Animations override (w-appearance). Read on
  # every render (not baked once into hyprland.lua), so it also survives a later
  # theme switch. Root/skel has no per-user override to apply.
  local anim_enabled=true
  if [[ $EUID -ne 0 ]]; then
    # shellcheck source=/dev/null
    source /usr/lib/w/w-conf-lib.sh
    [[ "$(wconf_get appearance MOTION "")" == "off" ]] && anim_enabled=false
  fi
  echo "w-style: rendering motion (Hyprland animations + Quickshell motion.json)..."

  write_user_file "$HYPR_ANIM_REL" <<EOF
-- W Linux — generated by w-style (apply motion). Do not edit; edit the active
-- theme's motion.conf (default /etc/w/themes/w/motion.conf).
-- Self-applying Lua module require()d by hyprland.lua: declares the shared \`snap\`
-- curve and the animation leaves. Speeds are deciseconds (ms/100); the \`snap\`
-- bezier is shared with Quickshell (motion.json below).
hl.config({ animations = { enabled = $anim_enabled } })
hl.curve("snap", { type = "bezier", points = $(bezier_points) })
hl.animation({ leaf = "windows",    enabled = true,  speed = $(ms_to_ds "$W_MOTION_BASE"), bezier = "snap" })
hl.animation({ leaf = "windowsIn",  enabled = false })
hl.animation({ leaf = "fade",       enabled = true,  speed = $(ms_to_ds "$W_MOTION_BASE"), bezier = "snap" })
hl.animation({ leaf = "workspaces", enabled = true,  speed = $(ms_to_ds "$W_MOTION_BASE"), bezier = "snap" })
hl.animation({ leaf = "layers",     enabled = true,  speed = $(ms_to_ds "$W_MOTION_SLOW"), bezier = "snap", style = "fade" })
EOF

  write_user_file "$QS_MOTION_REL" <<EOF
{
  "_comment": "W Linux — generated by w-style. Do not edit; edit the active theme's motion.conf (default /etc/w/themes/w/motion.conf).",
  "fast": $W_MOTION_FAST,
  "base": $W_MOTION_BASE,
  "slow": $W_MOTION_SLOW,
  "bezier": [$W_MOTION_BEZIER]
}
EOF

  hypr_reload
  echo "w-style: motion done."
}
