# w-style module: imv (user-scope) — Wayland image viewer.
# imv's config is a single file with no include directive and almost no chrome
# (the content IS the image), so the axis owns the whole ~/.config/imv/config:
# constant behaviour + brand colours from Tier-2 role tokens. imv colours are
# 6-hex with NO leading '#'. NOT live (read at startup). Band 500 = app/config.
DESC="imv image-viewer palette"

IMV_CONFIG_REL=".config/imv/config"

render_user() {
  local theme_dir; theme_dir="$(w_userscope_theme_dir)"
  load_conf "$theme_dir"
  load_font "$(resolve_theme_file "$theme_dir" font.conf)"
  echo "w-style: rendering imv config..."

  # imv wants bare 6-hex colours.
  local bg="${W_APP_BG#\#}" fg="${W_ON_SURFACE#\#}" surf="${W_SURFACE#\#}"

  write_user_file "$IMV_CONFIG_REL" <<EOF
# W Linux — generated by w-style. Do not edit; edit the theme's theme.conf.
[options]
background = $bg
overlay = false
overlay_font = $W_FONT_MONO:$W_FONT_MONO_SIZE
overlay_text_color = $fg
overlay_text_alpha = ff
overlay_background_color = $surf
overlay_background_alpha = c8
overlay_text = \${imv_current_file}   [\${imv_width}x\${imv_height}]   \${imv_current_index}/\${imv_file_count}
scaling_mode = shrink
upscaling_method = nearest_neighbour
EOF

  echo "w-style: imv done (applies to newly launched imv instances)."
}
