# w-style module: git (user-scope) — diff/pager colours for git + delta.
#
# Ships INSIDE the dev W-Pack (source of truth); `w-pack install dev` drops this
# axis into the w-style modules.d drop-in root and renders it. Core w-style carries
# no reference to git tooling → the axis exists iff the bundle is installed, so no
# presence-guard is needed (packs.md "bundle self-containment", pack-dev.md).
#
# OWNERSHIP — three files, and nothing W writes is ever the user's:
#   ~/.config/git/config       W's (bundle manifest, class `managed`); it
#                              `[include]`s the file below and sets `[delta]
#                              features = w`, delta's own convention for themes.
#   ~/.config/w/git-theme.conf W's, rendered HERE, deliberately NOT in the manifest
#                              (that would be two writers for one file).
#   ~/.gitconfig               the USER's, seeded once as an empty stub.
# Git reads the two global files in that order and the later one wins, so the user
# overrides W key by key — while W stays free to change its own file on any update.
#
# LIVE: git re-reads its config on every single invocation, so a `w-theme set` shows
# up in the very next `git diff` — no relogin, no restart. Band 500 = terminal/CLI.
#
# No new theme tokens: diff/pager roles map onto the existing Tier-2 semantic roles
# and the Tier-3 terminal pigments (W_TERM_ANSI_*), same as the helix/micro axes —
# one theme.conf recolours the editors, the terminal and now the diffs alike.
DESC="git + delta diff colours (CLI)"

GIT_THEME_REL=".config/w/git-theme.conf"

render_user() {
  load_conf "$(w_userscope_theme_dir)"
  echo "w-style: rendering git theme..."

  # delta marks a feature as a "theme" (and picks its background defaults) with
  # EXACTLY ONE of `dark`/`light` — upstream's themes.gitconfig never emits both, and
  # these are flag-shaped options, so emitting the other one as `false` is a needless
  # risk. W_APPEARANCE already carries the choice for every W theme.
  local mode="dark"
  [[ "$W_APPEARANCE" == "light" ]] && mode="light"

  # NOTE ON QUOTING: in a git config file `#` starts a comment unless the value is
  # double-quoted — every hex colour below MUST stay quoted or git silently reads a
  # truncated (empty) value.
  write_user_file "$GIT_THEME_REL" <<EOF
# W Linux — generated by w-style. Do not edit; edit the theme's theme.conf.
# Included from ~/.config/git/config. Colours only: behavioural settings belong in
# your own ~/.gitconfig, which git loads after this and therefore wins.

# ── delta ─────────────────────────────────────────────────────────────────────
# Activated by \`[delta] features = w\` in ~/.config/git/config.
#
# Added/removed lines are coloured in the FOREGROUND rather than with tinted
# backgrounds: W's palette has a container role for red (W_DANGER_CONTAINER) but no
# counterpart for green, and a half-tinted diff reads worse than an untinted one.
# Introducing a diff-background token pair would mean editing theme.conf for every
# theme — out of scope for a bundle axis (packs.md self-containment).
[delta "w"]
	$mode = true

	# Syntax highlighting inside the diff rides the terminal's ANSI palette — the
	# same trick the shell axis uses for bat (BAT_THEME=ansi), so delta follows the
	# W theme without generating a .tmTheme. delta resolves this name through bat's
	# HighlightingAssets, and an unknown name only warns and falls back to bat's
	# default — it cannot break the pager. \`syntax-theme = none\` disables syntax
	# highlighting entirely (structural colours stay).
	#
	# The explicit \`$mode = true\` above wins over whatever mode this theme name
	# would imply, so a future light W theme stays light here.
	syntax-theme = ansi

	line-numbers = true
	keep-plus-minus-markers = true

	# Diff body
	plus-style = "$W_TERM_ANSI_GREEN"
	plus-emph-style = "$W_TERM_ANSI_BRIGHT_GREEN" bold
	minus-style = "$W_TERM_ANSI_RED"
	minus-emph-style = "$W_TERM_ANSI_BRIGHT_RED" bold
	zero-style = syntax
	whitespace-error-style = "$W_ON_DANGER_CONTAINER" "$W_DANGER_CONTAINER"

	# File header
	file-style = "$W_PRIMARY" bold
	file-decoration-style = "$W_SURFACE_VARIANT" ul

	# Hunk header
	hunk-header-style = file line-number syntax
	hunk-header-file-style = "$W_ON_SURFACE"
	hunk-header-line-number-style = "$W_PRIMARY"
	hunk-header-decoration-style = "$W_SURFACE_VARIANT" box ul

	# Line-number gutter
	line-numbers-left-style = "$W_ON_SURFACE_VARIANT"
	line-numbers-right-style = "$W_ON_SURFACE_VARIANT"
	line-numbers-minus-style = "$W_TERM_ANSI_RED"
	line-numbers-plus-style = "$W_TERM_ANSI_GREEN"
	line-numbers-zero-style = "$W_ON_SURFACE_VARIANT"

	# Commit header (git show / log)
	commit-style = "$W_PRIMARY" bold
	commit-decoration-style = "$W_SURFACE_VARIANT" box ul

	# blame / grep
	blame-code-style = syntax
	blame-palette = "$W_APP_BG" "$W_SURFACE_DIM" "$W_SURFACE" "$W_SURFACE_VARIANT"
	grep-file-style = "$W_PRIMARY"
	grep-line-number-style = "$W_ON_SURFACE_VARIANT"

	# Merge conflicts (pairs with merge.conflictStyle = zdiff3 in ~/.gitconfig)
	merge-conflict-begin-symbol = ~
	merge-conflict-end-symbol = ~
	merge-conflict-ours-diff-header-style = "$W_TERM_ANSI_YELLOW" bold
	merge-conflict-ours-diff-header-decoration-style = "$W_SURFACE_VARIANT" box
	merge-conflict-theirs-diff-header-style = "$W_TERM_ANSI_YELLOW" bold
	merge-conflict-theirs-diff-header-decoration-style = "$W_SURFACE_VARIANT" box

# ── plain git ─────────────────────────────────────────────────────────────────
# delta only pages diff-like output. Everything else — status, branch, log
# decorations, grep, the interactive add UI — is coloured by git itself, so it gets
# the W palette here too.
[color "diff"]
	meta = "$W_ON_SURFACE_VARIANT"
	frag = "$W_PRIMARY"
	func = "$W_TERM_ANSI_BLUE"
	old = "$W_TERM_ANSI_RED"
	new = "$W_TERM_ANSI_GREEN"
	commit = "$W_TERM_ANSI_YELLOW"
	whitespace = "$W_ON_DANGER_CONTAINER" "$W_DANGER_CONTAINER"

[color "status"]
	header = "$W_ON_SURFACE_VARIANT"
	added = "$W_TERM_ANSI_GREEN"
	updated = "$W_TERM_ANSI_GREEN"
	changed = "$W_TERM_ANSI_YELLOW"
	untracked = "$W_TERM_ANSI_RED"
	unmerged = "$W_DANGER"
	branch = "$W_PRIMARY" bold
	nobranch = "$W_ERROR"
	localBranch = "$W_PRIMARY"
	remoteBranch = "$W_TERM_ANSI_CYAN"

[color "branch"]
	current = "$W_PRIMARY" bold
	local = "$W_ON_SURFACE"
	remote = "$W_TERM_ANSI_CYAN"
	upstream = "$W_TERM_ANSI_BRIGHT_CYAN"
	plain = "$W_ON_SURFACE"

[color "decorate"]
	branch = "$W_PRIMARY" bold
	remoteBranch = "$W_TERM_ANSI_CYAN"
	tag = "$W_TERM_ANSI_YELLOW"
	stash = "$W_TERM_ANSI_MAGENTA"
	HEAD = "$W_ERROR" bold
	grafted = "$W_ON_SURFACE_VARIANT"

[color "grep"]
	filename = "$W_PRIMARY"
	linenumber = "$W_ON_SURFACE_VARIANT"
	separator = "$W_ON_SURFACE_VARIANT"
	match = "$W_TERM_ANSI_YELLOW"

[color "interactive"]
	prompt = "$W_PRIMARY"
	header = "$W_ON_SURFACE_VARIANT"
	help = "$W_ON_SURFACE_VARIANT"
	error = "$W_ERROR"

[color "remote"]
	hint = "$W_ON_SURFACE_VARIANT"
	success = "$W_TERM_ANSI_GREEN"
	warning = "$W_TERM_ANSI_YELLOW"
	error = "$W_ERROR"

[color "push"]
	error = "$W_ERROR"
EOF

  echo "w-style: git done (live — the next git command already uses it)."
}
