# w-style module: atuin (user-scope) — shell-history TUI theme (Tier-2 roles).
# config.toml selects name "w". NOT live (next atuin invocation). Band 500 = CLI.
DESC="atuin shell-history theme (TUI)"

ATUIN_THEME_REL=".config/atuin/themes/w.toml"

render_user() {
  load_conf "$(w_userscope_theme_dir)"
  echo "w-style: rendering atuin theme..."

  write_user_file "$ATUIN_THEME_REL" <<EOF
# W Linux — generated by w-style. Do not edit; edit the theme's theme.conf.
[theme]
name = "w"

[colors]
Base = "$W_ON_SURFACE"
Title = "$W_PRIMARY"
Important = "$W_PRIMARY"
Guidance = "$W_ON_SURFACE_VARIANT"
Annotation = "$W_ON_SURFACE_VARIANT"
AlertInfo = "$W_PRIMARY"
AlertWarn = "$W_ON_ERROR_CONTAINER"
AlertError = "$W_ERROR"
EOF

  echo "w-style: atuin done (applies to the next atuin invocation)."
}
