# w-style module: hyprlock (user-scope) — lock-screen chrome colors + font +
# scale-aware geometry. Renders into hyprlock-colors.conf, which hyprlock.conf
# sources. NOT live (and need not be): hyprlock reads its config fresh on every
# lock, so a running session never needs reloading — the next lock picks up the
# theme. Background blur/screenshot is configured in hyprlock.conf, not here.
# Pulls the theme's font + geometry axes (like qt) so labels/rounding follow the
# active UI. Band 100 = compositor + shell surfaces.
#
# hyprlock draws its own widgets (unlike Quickshell/Qt clients, which auto-
# multiply logical pixels by the Wayland output scale) at raw output pixels, so
# without help its font sizes/field/positions never react to `w-monitor scale`.
# Widgets are scoped to the primary output only (`$w_lock_primary`, sourced from
# w-monitor's `~/.local/state/w/displays.json` — the same source the bar reads)
# — hyprlock's `monitor =` left blank mirrors a widget on every connected
# output, which duplicated the password field on multi-monitor rigs; only
# `background` stays unscoped so the blur still covers every screen. Geometry
# below is the design baseline at scale 1.0 (matches hyprlock.conf's old
# literals), scaled to the primary output's live Hyprland scale. Falls back to
# scale=1/no primary-scoping (today's behaviour) when there's no live session
# to query (e.g. root render into skel at install time).
DESC="hyprlock lock-screen colors + font + scale-aware geometry"

HYPRLOCK_COLORS_REL=".config/hypr/hyprlock-colors.conf"

# Scale one baseline (scale=1.0) pixel value to the primary output's live scale.
# Rounds to nearest int, correct for negative offsets too (position vars can be
# negative). $scale defaults to "1" when no live primary scale was found.
scl() { awk -v b="$1" -v s="${scale:-1}" 'BEGIN{v=b*s; printf "%d", (v>=0)?v+0.5:v-0.5}'; }

render_user() {
  local theme_dir; theme_dir="$(w_userscope_theme_dir)"
  load_conf "$theme_dir"
  load_font "$(resolve_theme_file "$theme_dir" font.conf)"
  load_geometry "$(resolve_theme_file "$theme_dir" geometry.conf)"
  echo "w-style: rendering hyprlock colors..."

  local primary="" scale="1"
  # HOME is not guaranteed: w-style renders as root from w-firstboot, a systemd
  # SYSTEM unit, and systemd exports HOME only for units with User=. A bare $HOME
  # under `set -u` aborted this axis on every fresh install (release gate,
  # 2026-08-06). An unresolvable home simply means "no session state to read" —
  # the [[ -r ]] below then skips it and the scale falls back to 1, exactly as it
  # does for a root render on a machine where the user has never set a monitor up.
  local state="${XDG_STATE_HOME:-${HOME:-/nonexistent}/.local/state}/w/displays.json"
  if command -v jq &>/dev/null && [[ -r "$state" ]]; then
    primary="$(jq -r '.primary // empty' "$state" 2>/dev/null)"
  fi
  if [[ -n "$primary" ]] && command -v hyprctl &>/dev/null; then
    local live_scale
    live_scale="$(hyprctl monitors -j 2>/dev/null \
      | jq -r --arg o "$primary" '.[] | select(.name==$o) | .scale' 2>/dev/null)"
    [[ -n "$live_scale" && "$live_scale" != "null" ]] && scale="$live_scale"
  fi

  write_user_file "$HYPRLOCK_COLORS_REL" <<EOF
# W Linux — generated by w-style. Do not edit; edit the theme's theme.conf/font.conf/geometry.conf.
\$w_lock_inner = $(hypr_rgba "$W_LOCK_INNER")
\$w_lock_outer = $(hypr_rgba "$W_LOCK_OUTER")
\$w_lock_font = $(hypr_rgba "$W_LOCK_FONT")
\$w_lock_placeholder = $(hypr_rgba "$W_LOCK_PLACEHOLDER")
\$w_lock_check = $(hypr_rgba "$W_LOCK_CHECK")
\$w_lock_fail = $(hypr_rgba "$W_LOCK_FAIL")
\$w_lock_caps = $(hypr_rgba "$W_LOCK_CAPS")
\$w_lock_text = $(hypr_rgba "$W_LOCK_TEXT")
\$w_lock_text_dim = $(hypr_rgba "$W_LOCK_TEXT_DIM")
\$w_lock_bg = $(hypr_rgba "$W_LOCK_BG")
\$w_lock_bg_fallback = $(hypr_rgba "$W_SURFACE_VARIANT")
\$w_lock_font_family = $W_FONT_UI
\$w_lock_rounding = $(scl "$W_GEO_RADIUS")

# Primary-only widget scoping + scale (see comment above); \$w_lock_primary
# empty = hyprlock's own default (every monitor), matching pre-scale behaviour.
\$w_lock_primary = $primary
\$w_lock_clock_size = $(scl 92)
\$w_lock_clock_pos = $(scl 0), $(scl 150)
\$w_lock_date_size = $(scl 18)
\$w_lock_date_pos = $(scl 0), $(scl 80)
\$w_lock_layout_size = $(scl 14)
\$w_lock_layout_pos = $(scl 0), $(scl -100)
\$w_lock_field_size = $(scl 300), $(scl 54)
\$w_lock_field_outline = $(scl 2)
\$w_lock_field_pos = $(scl 0), $(scl -40)
EOF

  echo "w-style: hyprlock done."
}
