# w-style module: satty (user-scope) — screenshot annotation UI theming.
# satty is a GTK4/libadwaita app, so its window chrome is already themed by the
# `gtk` axis (band 200). This axis owns the parts satty exposes through its own
# config: the annotation colour palette, the text-annotation font, and a few
# behavioural defaults. satty reads ~/.config/satty/config.toml once at startup,
# so this is NOT live (applies to the next launch), like the TUI axes.
#
# The save path is deliberately NOT set here: w-screenshot passes it at runtime
# (--output-filename) because this render lands in /etc/skel as root at install
# time, where the target user's $HOME is unknown. Band 400 = per-app GUI config.
DESC="satty screenshot annotation palette/font"

SATTY_CONFIG_REL=".config/satty/config.toml"

render_user() {
  local theme_dir; theme_dir="$(w_userscope_theme_dir)"
  load_conf "$theme_dir"
  load_font "$(resolve_theme_file "$theme_dir" font.conf)"
  echo "w-style: rendering satty config..."

  # Bright, mutually-distinct annotation colours pulled from the theme's ANSI
  # brights, with the brand accent first (default drawing colour).
  write_user_file "$SATTY_CONFIG_REL" <<EOF
# W Linux — generated by w-style. Do not edit; edit the theme's theme.conf/font.conf.
# satty screenshot annotation tool. Window chrome is themed by the gtk axis; this
# file carries the annotation palette, font and behavioural defaults. The save
# path is supplied by w-screenshot at runtime (--output-filename), not here.
[general]
copy-command = "wl-copy"
initial-tool = "brush"
early-exit = false
save-after-copy = false
default-hide-toolbars = false
primary-highlighter = "block"
corner-roundness = 12
actions-on-enter = ["save-to-clipboard"]

[font]
family = "$W_FONT_UI"
style = "Regular"

[color-palette]
palette = [
  "$W_PRIMARY",
  "$W_TERM_ANSI_BRIGHT_RED",
  "$W_TERM_ANSI_BRIGHT_YELLOW",
  "$W_TERM_ANSI_BRIGHT_GREEN",
  "$W_TERM_ANSI_BRIGHT_BLUE",
  "$W_TERM_ANSI_BRIGHT_MAGENTA",
  "$W_TERM_ANSI_BRIGHT_CYAN",
  "$W_ON_SURFACE",
]
custom = [
  "$W_PRIMARY",
  "$W_ERROR",
]
EOF

  echo "w-style: satty done (applies to the next satty launch)."
}
