# w-i18n-lib.sh — runtime string lookup for the W scripts (shared, sourced).
#
# The bash side of the translation layer whose source of truth is i18n/ and whose
# shipped form is /usr/share/w/i18n/ (generated by w-i18n-gen). Two APIs, one
# language resolver:
#
#   w_t <key> [printf-args…]     → the translated text, printf-formatted
#   w_help <tool>                → the tool's translated help text, or non-zero
#
# w_t covers strings that land on a GRAPHICAL surface — desktop notifications and
# their action buttons. Canon: i18n/scripts.json.
#
# w_help covers the other half of what a user reads: `w-<tool> help`, and through
# its `Info:` line the w-info catalog. Canon: i18n/help/<lang>/w-<tool>.txt, which
# holds TRANSLATIONS ONLY — the English original stays in the tool's own usage()
# heredoc, because that heredoc is what w-info parses, what w-docs-refgen renders
# the English reference from, and what prints when no catalog is installed. See
# config-i18n.md §5a.
#
# Still English either way: runtime terminal output (`echo`, `die`, progress).
# That layer is a per-call-site job, not an architecture one — w_t is ready for it.
#
# Language resolution matches Quickshell's Strings.qml exactly — LC_MESSAGES, else
# LANG, 2-letter code, fallback en. It has to: the same event can surface both as
# a notification (here) and in the shell UI (there), and the two disagreeing about
# which language is active would be worse than either being wrong.
#
# en.conf is loaded FIRST and the active language overlaid on top, so a key that
# a translation has not reached yet falls back per-key to English rather than
# showing a raw key name. A missing catalog entirely degrades to printing the key.

W_I18N_DIR="${W_I18N_DIR:-/usr/share/w/i18n}"
declare -gA W_I18N_MSG=()
_w_i18n_loaded=""

# 2-letter code of the active message locale.
_w_i18n_lang() {
  local l="${LC_MESSAGES:-}"
  [[ -n "$l" ]] || l="${LANG:-}"
  l="${l%%.*}"; l="${l%%@*}"; l="${l%%_*}"
  echo "${l:-en}"
}

# Line-wise parse, never `source`: the values are raw text with spaces, quotes and
# ':' in them (the same reason the installer's tui.sh parses its dicts by hand).
_w_i18n_load() {
  [[ -n "$_w_i18n_loaded" ]] && return 0
  _w_i18n_loaded=1
  local lang file line k
  lang="$(_w_i18n_lang)"
  for file in "$W_I18N_DIR/en.conf" "$W_I18N_DIR/$lang.conf"; do
    [[ -r "$file" ]] || continue
    while IFS= read -r line || [[ -n "$line" ]]; do
      [[ "$line" == \#* || "$line" != *=* ]] && continue
      k="${line%%=*}"
      [[ -n "$k" ]] && W_I18N_MSG["$k"]="${line#*=}"
    done < "$file"
  done
  return 0
}

w_t() {
  local key="${1:-}"
  shift || true
  _w_i18n_load
  local fmt="${W_I18N_MSG[$key]:-$key}"
  # The translation IS the format string — that is the point, and w-i18n-gen
  # asserts every language carries the same placeholders as en, so a mismatched
  # conversion cannot reach here.
  # shellcheck disable=SC2059
  printf "$fmt" "$@"
}

# A help text names real paths through the variables that hold them ($CONF,
# $STATE_FILE, …) — 45 such references across the tools. The shell expands them
# inside the heredoc; a file has no shell, so we expand them here, by NAME LOOKUP
# ONLY. Never eval: this text is data, and a `$(…)` in it must stay the four
# characters it is. w-i18n-gen asserts a translation references exactly the
# variables its English original does, so an unset name here means a bug, not a
# translation choice — it is re-emitted verbatim rather than silently blanked.
# `\$` is a literal dollar, exactly as inside the heredoc this translates — the
# translation files reuse the source's own escaping convention rather than
# inventing a second one.
_w_help_expand() {
  local s="$1" out="" pre name
  # `[^$]*` cannot cross a '$', so this always anchors on the leftmost one; the
  # escape is then decided by what that run ENDS with, because a leading group
  # this greedy would otherwise swallow the backslash itself.
  while [[ "$s" =~ ^([^$]*)\$\{?([A-Za-z_][A-Za-z0-9_]*)\}?(.*)$ ]]; do
    pre="${BASH_REMATCH[1]}"; name="${BASH_REMATCH[2]}"; s="${BASH_REMATCH[3]}"
    if [[ "$pre" == *\\ ]]; then out+="${pre%\\}\$$name"
    elif [[ -v "$name" ]]; then out+="$pre${!name}"
    else out+="$pre\$$name"; fi
  done
  printf '%s%s\n' "$out" "$s"
}

# Print <tool>'s translated help; return non-zero when there is none, which is
# the caller's cue to print its own English heredoc:
#
#   usage() {
#     if w_help w-locale; then return 0; fi
#     cat <<EOF … EOF
#   }
#
# English is never a file here (it is the heredoc), so `en` short-circuits — that
# is not an optimization, it is the rule that keeps one English original.
# Path of <tool>'s translated help, or non-zero when there is none. Split out of
# w_help because w-info wants the FILE, not the rendered text: it greps the
# `Info:` line out of every tool to build its catalog, and re-implementing the
# language resolution there would be the one place it could disagree with the
# help the same catalog points at.
w_help_file() {
  local tool="${1:-}" lang
  [[ -n "$tool" ]] || return 1
  lang="$(_w_i18n_lang)"
  [[ "$lang" == "en" ]] && return 1
  local file="$W_I18N_DIR/help/$lang/$tool.txt"
  [[ -r "$file" ]] || return 1
  printf '%s\n' "$file"
}

w_help() {
  local file line
  file="$(w_help_file "${1:-}")" || return 1
  while IFS= read -r line || [[ -n "$line" ]]; do
    _w_help_expand "$line"
  done <"$file"
  return 0
}
