# w-style module: zathura (user-scope) — keyboard-driven document viewer
# (PDF/EPUB/CBZ/XPS via zathura-pdf-mupdf). zathura has no include directive, so
# the axis owns the whole ~/.config/zathura/zathurarc: constant behaviour +
# brand colours + page recolour. The GTK3 window chrome is themed live by the W
# `gtk` axis; this file colours the document area, statusbar, inputbar,
# completion and (under `recolor`) the page itself. NOT live (read at startup).
# Band 500 = app/config tier.
DESC="zathura document-viewer palette"

ZATHURA_CONFIG_REL=".config/zathura/zathurarc"

render_user() {
  local theme_dir; theme_dir="$(w_userscope_theme_dir)"
  load_conf "$theme_dir"
  load_font "$(resolve_theme_file "$theme_dir" font.conf)"
  echo "w-style: rendering zathura config..."

  write_user_file "$ZATHURA_CONFIG_REL" <<EOF
# W Linux — generated by w-style. Do not edit; edit the theme's theme.conf.

# ── Behaviour ────────────────────────────────────────────────────────────────
set selection-clipboard clipboard
set adjust-open "best-fit"
set scroll-page-aware true
set statusbar-h-padding 8
set statusbar-v-padding 6
set font "$W_FONT_MONO $W_FONT_MONO_SIZE"
set window-title-basename true
set guioptions "s"

# ── Chrome palette ───────────────────────────────────────────────────────────
set default-bg              "$W_APP_BG"
set default-fg              "$W_ON_SURFACE"
set statusbar-bg            "$W_SURFACE"
set statusbar-fg            "$W_ON_SURFACE"
set inputbar-bg            "$W_SURFACE"
set inputbar-fg            "$W_ON_SURFACE"
set notification-bg         "$W_SURFACE"
set notification-fg         "$W_ON_SURFACE"
set notification-warning-bg "$W_SURFACE"
set notification-warning-fg "$W_ON_ERROR_CONTAINER"
set notification-error-bg   "$W_DANGER_CONTAINER"
set notification-error-fg   "$W_ON_DANGER_CONTAINER"
set completion-bg           "$W_SURFACE"
set completion-fg           "$W_ON_SURFACE"
set completion-group-bg     "$W_SURFACE_DIM"
set completion-group-fg     "$W_ON_SURFACE_VARIANT"
set completion-highlight-bg "$W_PRIMARY_CONTAINER"
set completion-highlight-fg "$W_ON_PRIMARY_CONTAINER"
set index-bg                "$W_APP_BG"
set index-fg                "$W_ON_SURFACE"
set index-active-bg         "$W_PRIMARY_CONTAINER"
set index-active-fg         "$W_ON_PRIMARY_CONTAINER"
set highlight-color         "$W_PRIMARY"
set highlight-active-color  "$W_ERROR"
set render-loading-bg       "$W_APP_BG"
set render-loading-fg       "$W_ON_SURFACE"

# ── Page recolour (dark reading; toggle live with 'r') ───────────────────────
set recolor true
set recolor-keephue true
set recolor-lightcolor "$W_APP_BG"
set recolor-darkcolor  "$W_ON_SURFACE"
EOF

  echo "w-style: zathura done (applies to newly launched zathura instances)."
}
