# w-style module: helix (user-scope) — terminal editor theme. config.toml
# (skel) selects theme "w"; helix reads the theme at startup / on `:theme`, so
# this is NOT live (next invocation), like micro/btop/atuin.
# No new theme tokens: helix's highlight scopes map onto existing Tier-2 roles +
# the Tier-3 terminal ANSI pigments (W_TERM_ANSI_*), like the other TUI axes —
# same role set as the `micro` axis, just Helix's TOML key/table syntax instead
# of micro's `color-link`. Band 500 = terminal/CLI.
DESC="helix editor theme (TUI)"

HELIX_THEME_REL=".config/helix/themes/w.toml"

render_user() {
  load_conf "$(w_userscope_theme_dir)"
  echo "w-style: rendering helix theme..."

  write_user_file "$HELIX_THEME_REL" <<EOF
# W Linux — generated by w-style. Do not edit; edit the theme's theme.conf.

# Core UI surfaces
"ui.background" = { fg = "$W_TERM_FG", bg = "$W_TERM_BG" }
"ui.text" = "$W_TERM_FG"
"ui.text.focus" = "$W_ON_SURFACE"
"ui.cursor.primary" = { fg = "$W_TERM_BG", bg = "$W_PRIMARY" }
"ui.cursor.match" = { fg = "$W_ON_PRIMARY_CONTAINER", bg = "$W_PRIMARY_CONTAINER" }
"ui.selection" = { fg = "$W_TERM_SELECTION_FG", bg = "$W_TERM_SELECTION_BG" }
"ui.linenr" = { fg = "$W_ON_SURFACE_VARIANT", bg = "$W_APP_BG" }
"ui.linenr.selected" = { fg = "$W_PRIMARY", bg = "$W_APP_BG", modifiers = ["bold"] }
"ui.virtual.whitespace" = "$W_ON_SURFACE_VARIANT"
"ui.virtual.indent-guide" = "$W_ON_SURFACE_VARIANT"
"ui.virtual.ruler" = { bg = "$W_SURFACE" }
"ui.virtual.wrap" = "$W_ON_SURFACE_VARIANT"

# Chrome
"ui.statusline" = { fg = "$W_ON_SURFACE", bg = "$W_SURFACE_VARIANT" }
"ui.statusline.inactive" = { fg = "$W_ON_SURFACE_VARIANT", bg = "$W_SURFACE" }
"ui.bufferline" = { fg = "$W_ON_SURFACE_VARIANT", bg = "$W_SURFACE" }
"ui.bufferline.active" = { fg = "$W_ON_PRIMARY_CONTAINER", bg = "$W_PRIMARY_CONTAINER" }
"ui.popup" = { fg = "$W_ON_SURFACE", bg = "$W_SURFACE" }
"ui.window" = { fg = "$W_SURFACE_VARIANT" }
"ui.help" = { fg = "$W_ON_SURFACE", bg = "$W_SURFACE" }
"ui.menu" = { fg = "$W_ON_SURFACE", bg = "$W_SURFACE" }
"ui.menu.selected" = { fg = "$W_ON_PRIMARY_CONTAINER", bg = "$W_PRIMARY_CONTAINER" }
"ui.gutter" = { bg = "$W_APP_BG" }

# Diagnostics / diff
"warning" = "$W_TERM_ANSI_YELLOW"
"error" = "$W_ERROR"
"info" = "$W_TERM_ANSI_BLUE"
"hint" = "$W_TERM_ANSI_CYAN"
"diagnostic.error" = { underline = { color = "$W_ERROR", style = "curl" } }
"diagnostic.warning" = { underline = { color = "$W_TERM_ANSI_YELLOW", style = "curl" } }
"diagnostic.info" = { underline = { color = "$W_TERM_ANSI_BLUE", style = "curl" } }
"diagnostic.hint" = { underline = { color = "$W_TERM_ANSI_CYAN", style = "curl" } }
"diff.plus" = "$W_TERM_ANSI_GREEN"
"diff.delta" = "$W_TERM_ANSI_YELLOW"
"diff.minus" = "$W_TERM_ANSI_RED"

# Syntax highlighting
"comment" = { fg = "$W_ON_SURFACE_VARIANT", modifiers = ["italic"] }
"constant" = "$W_TERM_ANSI_CYAN"
"constant.numeric" = "$W_TERM_ANSI_BRIGHT_MAGENTA"
"constant.character.escape" = "$W_TERM_ANSI_BRIGHT_MAGENTA"
"string" = "$W_TERM_ANSI_GREEN"
"string.special" = "$W_TERM_ANSI_BRIGHT_CYAN"
"function" = "$W_TERM_ANSI_BLUE"
"variable" = "$W_TERM_FG"
"variable.builtin" = "$W_TERM_ANSI_RED"
"variable.parameter" = "$W_ON_SURFACE"
"type" = "$W_TERM_ANSI_BRIGHT_CYAN"
"type.builtin" = "$W_PRIMARY"
"keyword" = "$W_PRIMARY"
"keyword.control" = { fg = "$W_PRIMARY", modifiers = ["bold"] }
"operator" = "$W_ON_SURFACE_VARIANT"
"punctuation" = "$W_ON_SURFACE_VARIANT"
"special" = "$W_TERM_ANSI_RED"
"tag" = "$W_TERM_ANSI_RED"
"attribute" = "$W_TERM_ANSI_YELLOW"
"namespace" = "$W_TERM_ANSI_BRIGHT_CYAN"
"label" = "$W_TERM_ANSI_YELLOW"

# Markup (markdown etc.)
"markup.heading" = { fg = "$W_PRIMARY", modifiers = ["bold"] }
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.link.url" = { fg = "$W_TERM_ANSI_GREEN", modifiers = ["underlined"] }
"markup.raw" = "$W_TERM_ANSI_CYAN"
EOF

  echo "w-style: helix done (applies to the next helix invocation)."
}
