# w-style module: geometry (user-scope) — interface geometry shared across W's
# own surfaces, rendered for both Hyprland (geometry.lua: window gaps/border/
# rounding data table require()d by hyprland.lua) and Quickshell (geometry.json: radius/radiusSm/
# padding/gap base scale plus the `bar` shape block). Source is the active theme's
# geometry.conf, falling back to baseline `w` when omitted. Both files written
# in-place; Hyprland is reloaded, Quickshell's Geometry.qml singleton picks up
# geometry.json via FileView. GTK/Qt widget shape and GRUB/Plymouth are out of scope
# (baked per-toolkit / absolute layouts). Band 100 = compositor + shell surfaces.
DESC="interface geometry (Hyprland + Quickshell)"

HYPR_GEOMETRY_REL=".config/hypr/geometry.lua"
QS_GEOMETRY_REL=".config/quickshell/w/core/geometry.json"

# ── Value guards ──────────────────────────────────────────────────────────────
# geometry.json is parsed as a whole: one malformed value makes Geometry.qml keep its
# built-in defaults for the ENTIRE shell scale, not just the offending key. So every
# theme value is checked here and a bad one degrades to the baseline with a warning.

# geo_int <token-name> <value> <fallback> — emit a whole number.
geo_int() {
  if [[ "$2" =~ ^[0-9]+$ ]]; then
    printf '%s' "$2"
  else
    echo "w-style: $1='$2' is not a whole number — falling back to $3" >&2
    printf '%s' "$3"
  fi
}

# geo_radius <token-name> <value> <fallback> — emit a JSON scalar: a number, or the
# quoted keyword "pill" (resolved to half the element's height by the shell).
geo_radius() {
  if [[ "$2" =~ ^[0-9]+$ ]]; then
    printf '%s' "$2"
  elif [[ "$2" == "pill" ]]; then
    printf '"pill"'
  else
    echo "w-style: $1='$2' is neither a whole number nor 'pill' — falling back to $3" >&2
    printf '"%s"' "$3"
  fi
}

# geo_edge <token-name> <value> <fallback> — emit a quoted screen edge.
geo_edge() {
  if [[ "$2" == "top" || "$2" == "bottom" ]]; then
    printf '"%s"' "$2"
  else
    echo "w-style: $1='$2' is neither 'top' nor 'bottom' — falling back to $3" >&2
    printf '"%s"' "$3"
  fi
}

# geo_bool <token-name> <value> <fallback> — emit an unquoted true/false literal
# (valid in both Lua and JSON).
geo_bool() {
  if [[ "$2" == "true" || "$2" == "false" ]]; then
    printf '%s' "$2"
  else
    echo "w-style: $1='$2' is neither 'true' nor 'false' — falling back to $3" >&2
    printf '%s' "$3"
  fi
}

render_user() {
  load_geometry "$(resolve_theme_file "$(w_userscope_theme_dir)" geometry.conf)"
  echo "w-style: rendering geometry (Hyprland window metrics + Quickshell scale + bar)..."

  write_user_file "$HYPR_GEOMETRY_REL" <<EOF
-- W Linux — generated by w-style (apply geometry). Do not edit; edit the active
-- theme's geometry.conf (default /etc/w/themes/w/geometry.conf).
-- Lua data module require()d by hyprland.lua; values go into general{} + decoration{}.
return {
  gaps_in = $W_GEO_GAPS_IN,
  gaps_out = $W_GEO_GAPS_OUT,
  border = $W_GEO_WINDOW_BORDER,
  rounding = $W_GEO_WINDOW_ROUNDING,
  tab_height = $W_GEO_TAB_HEIGHT,
  tab_rounding = $W_GEO_TAB_ROUNDING,
  tab_gap = $W_GEO_TAB_GAP,
  tab_gap_in = $W_GEO_TAB_GAP_IN,
}
EOF

  write_user_file "$QS_GEOMETRY_REL" <<EOF
{
  "_comment": "W Linux — generated by w-style. Do not edit; edit the active theme's geometry.conf (default /etc/w/themes/w/geometry.conf). The \"bar\" block is the status bar's DEFAULT shape — bar.json (user-owned) may override any of it per element.",
  "radius": $W_GEO_RADIUS,
  "radiusSm": $W_GEO_RADIUS_SM,
  "padding": $W_GEO_PADDING,
  "gap": $W_GEO_GAP,
  "border": $W_GEO_BORDER,
  "gapsOut": $W_GEO_GAPS_OUT,
  "bar": {
    "position":     $(geo_edge   W_GEO_BAR_POSITION      "$W_GEO_BAR_POSITION"      top),
    "height":       $(geo_int    W_GEO_BAR_HEIGHT        "$W_GEO_BAR_HEIGHT"        32),
    "marginEdge":   $(geo_int    W_GEO_BAR_MARGIN_EDGE   "$W_GEO_BAR_MARGIN_EDGE"   6),
    "marginSide":   $(geo_int    W_GEO_BAR_MARGIN_SIDE   "$W_GEO_BAR_MARGIN_SIDE"   8),
    "radius":       $(geo_radius W_GEO_BAR_RADIUS        "$W_GEO_BAR_RADIUS"        pill),
    "radiusZone":   $(geo_radius W_GEO_BAR_RADIUS_ZONE   "$W_GEO_BAR_RADIUS_ZONE"   pill),
    "radiusButton": $(geo_radius W_GEO_BAR_RADIUS_BUTTON "$W_GEO_BAR_RADIUS_BUTTON" pill),
    "paddingV":     $(geo_int    W_GEO_BAR_PADDING_V     "$W_GEO_BAR_PADDING_V"     2),
    "paddingH":     $(geo_int    W_GEO_BAR_PADDING_H     "$W_GEO_BAR_PADDING_H"     2),
    "paddingZoneV": $(geo_int    W_GEO_BAR_PADDING_ZONE_V "$W_GEO_BAR_PADDING_ZONE_V" 0),
    "paddingZoneH": $(geo_int    W_GEO_BAR_PADDING_ZONE_H "$W_GEO_BAR_PADDING_ZONE_H" 8),
    "paddingGroup": $(geo_int    W_GEO_BAR_PADDING_GROUP "$W_GEO_BAR_PADDING_GROUP" 2),
    "gap":          $(geo_int    W_GEO_BAR_GAP           "$W_GEO_BAR_GAP"           4),
    "gapItem":      $(geo_int    W_GEO_BAR_GAP_ITEM      "$W_GEO_BAR_GAP_ITEM"      2),
    "gapButton":    $(geo_int    W_GEO_BAR_GAP_BUTTON    "$W_GEO_BAR_GAP_BUTTON"    4),
    "border":       $(geo_int    W_GEO_BAR_BORDER        "$W_GEO_BAR_BORDER"        0),
    "borderZone":   $(geo_int    W_GEO_BAR_BORDER_ZONE   "$W_GEO_BAR_BORDER_ZONE"   0),
    "borderButton": $(geo_int    W_GEO_BAR_BORDER_BUTTON "$W_GEO_BAR_BORDER_BUTTON" 0),
    "minSquare":    $(geo_bool   W_GEO_BAR_MIN_SQUARE    "$W_GEO_BAR_MIN_SQUARE"    true)
  }
}
EOF

  hypr_reload
  echo "w-style: geometry done."
}
