# w-style module: mangohud (user-scope) — MangoHud FPS/frametime overlay palette.
#
# Ships INSIDE the gaming W-Pack (source of truth); `w-pack install` drops this
# axis into the w-style modules.d drop-in root, `w-pack remove` takes it back.
# Core w-style carries no reference to MangoHud → the axis exists iff the
# bundle is installed (packs.md "bundle self-containment", pack-gaming.md).
#
# MangoHud reads a plain key=value config, colours as bare hex WITHOUT a
# leading '#' — the one gotcha of this axis: a token copied straight out of
# theme.conf (which DOES carry the '#') silently breaks the overlay's colour
# parser, so every colour line below strips it with `${VAR#\#}`. Not live:
# MangoHud reads MangoHud.conf once, when a game's overlay starts, so a theme
# switch mid-session recolours the NEXT launch, not the running one.
#
# Content keys (gpu/cpu/ram/vram/fps/frametime/engine/api, position, toggle
# key) are a sane default, not part of the theme — only the colour/size/alpha
# lines below come from theme.conf/font.conf/effects.conf. font_size and
# background_alpha reuse the SAME tokens the rest of W already renders from
# (W_FONT_MONO_SIZE, W_FX_SURFACE_OPACITY) rather than inventing overlay-only
# numbers. Band 400 = per-app GUI config.
DESC="MangoHud FPS/frametime overlay palette"

MANGOHUD_CONF_REL=".config/MangoHud/MangoHud.conf"

render_user() {
  local theme_dir; theme_dir="$(w_userscope_theme_dir)"
  load_conf "$theme_dir"
  load_font "$(resolve_theme_file "$theme_dir" font.conf)"
  load_effects "$(resolve_theme_file "$theme_dir" effects.conf)"
  echo "w-style: rendering MangoHud overlay..."

  local conf
  conf=$(cat <<EOF
### W Linux — generated by the w-style axis 400-mangohud. Do not edit; the
### palette comes from the active theme's theme.conf. Re-read at the next
### game launch (not live inside a running overlay). Toggle: Shift_F12.

gpu_stats
cpu_stats
ram
vram
fps
frametime
engine_version
api
position=top-right
toggle_hud=Shift_F12
font_size=${W_FONT_MONO_SIZE}
background_alpha=${W_FX_SURFACE_OPACITY}
text_color=${W_ON_SURFACE_BRIGHT#\#}
background_color=${W_SURFACE_DIM#\#}
gpu_color=${W_TERM_ANSI_CYAN#\#}
cpu_color=${W_TERM_ANSI_BLUE#\#}
vram_color=${W_TERM_ANSI_MAGENTA#\#}
ram_color=${W_TERM_ANSI_YELLOW#\#}
frametime_color=${W_TERM_ANSI_GREEN#\#}
engine_color=${W_ON_SURFACE_ACCENT#\#}
EOF
)

  # Sentinel first: under `set -u` a typo'd token name kills the command
  # substitution INSIDE its subshell, the assignment survives empty, and an
  # empty config would ship as a valid-looking file that disables the overlay
  # (MangoHud shows nothing rather than erroring on a blank config).
  if [[ -z "$conf" || ! "$conf" == *"text_color="* ]]; then
    echo "w-style: mangohud — rendered config is empty/malformed (token typo?), refusing to write." >&2
    return 1
  fi

  printf '%s\n' "$conf" | write_user_file "$MANGOHUD_CONF_REL"

  if [[ $EUID -eq 0 ]]; then
    echo "w-style: mangohud done (skel template; live accounts pick it up at their next login render)."
  else
    echo "w-style: mangohud done (next game launch shows the new colours)."
  fi
}
