# w-style module: effects (user-scope) — surface translucency + blur shared
# across W's own surfaces. Renders the two "native" targets that are LIVE:
#   Hyprland   → effects.lua (opacity_*/blur_* data table require()d by hyprland.lua;
#                used in decoration{} and the blur layer rules).
#   Quickshell → effects.json (surfaceOpacity/scrimOpacity + the bar's own chrome
#                pair, which a theme may drop to 0 for a "floating islands" bar);
#                the Effects.qml singleton picks it up via FileView.
# Concept ③ (foreign-app window background translucency) is consumed by the qt +
# gtk axes for actual app backgrounds (they load_effects when they render, like
# W_FONT_*; not live, so they refresh on the next apply/theme switch). Its value is
# ALSO threaded into effects.lua as `app_bg` so Hyprland can tint the group tab
# pills with the same translucency — a tab is a stand-in for its app window.
# Source is the active theme's effects.conf, falling back to baseline `w`.
# Band 100 = compositor + shell surfaces.
DESC="surface translucency + blur (Hyprland + Quickshell)"

HYPR_EFFECTS_REL=".config/hypr/effects.lua"
QS_EFFECTS_REL=".config/quickshell/w/core/effects.json"

render_user() {
  load_effects "$(resolve_theme_file "$(w_userscope_theme_dir)" effects.conf)"
  # Hub -> Appearance -> Settings -> Blur override (w-appearance). Read on every
  # render (not baked once into hyprland.lua), so it also survives a later theme
  # switch. Root/skel has no per-user override to apply.
  if [[ $EUID -ne 0 ]]; then
    # shellcheck source=/dev/null
    source /usr/lib/w/w-conf-lib.sh
    [[ "$(wconf_get appearance BLUR "")" == "off" ]] && W_FX_BLUR_ENABLED=false
  fi
  echo "w-style: rendering effects (Hyprland window opacity + blur + Quickshell surfaces)..."

  write_user_file "$HYPR_EFFECTS_REL" <<EOF
-- W Linux — generated by w-style (apply effects). Do not edit; edit the active
-- theme's effects.conf (default /etc/w/themes/w/effects.conf).
-- Lua data module require()d by hyprland.lua; values go into decoration{} (active/
-- inactive/fullscreen opacity + blur), the blur layer rules (ignore_alpha) and the
-- group tab pills (app_bg = concept ③ translucency, so tabs frost like app windows).
return {
  opacity_active = $W_FX_WINDOW_OPACITY_ACTIVE,
  opacity_inactive = $W_FX_WINDOW_OPACITY_INACTIVE,
  opacity_fullscreen = $W_FX_WINDOW_OPACITY_FULLSCREEN,
  blur_enabled = $W_FX_BLUR_ENABLED,
  blur_size = $W_FX_BLUR_SIZE,
  blur_passes = $W_FX_BLUR_PASSES,
  blur_ignore_alpha = $W_FX_BLUR_IGNORE_ALPHA,
  app_bg = $W_FX_APP_BG_OPACITY,
}
EOF

  # The blur triple goes to Quickshell too, not just to Hyprland: a modal that opens
  # INSIDE one of our own surfaces (the Hub's file picker) cannot be frosted by the
  # compositor — Hyprland blurs what is behind a surface, and both live in the same
  # one — so the shell reproduces the effect in-scene and needs the theme's numbers
  # (and the user's Blur=off override above) to match the rest of the desktop.
  write_user_file "$QS_EFFECTS_REL" <<EOF
{
  "_comment": "W Linux — generated by w-style. Do not edit; edit the active theme's effects.conf (default /etc/w/themes/w/effects.conf).",
  "surfaceOpacity": $W_FX_SURFACE_OPACITY,
  "scrimOpacity": $W_FX_SCRIM_OPACITY,
  "barOpacity": $W_FX_BAR_OPACITY,
  "barBorderOpacity": $W_FX_BAR_BORDER_OPACITY,
  "blurEnabled": $W_FX_BLUR_ENABLED,
  "blurSize": $W_FX_BLUR_SIZE,
  "blurPasses": $W_FX_BLUR_PASSES
}
EOF

  hypr_reload
  echo "w-style: effects done."
}
