# w-style module: lazydocker (user-scope) — container TUI theme.
#
# Ships INSIDE the containers W-Pack (source of truth); w-pack install drops this
# axis into the w-style modules.d drop-in root and renders it. Core w-style carries
# no reference to lazydocker → the axis exists iff the bundle is installed, so no
# presence-guard is needed (packs.md "bundle self-containment", pack-containers.md).
#
# lazydocker has no external theme file (unlike btop): gui.theme is inline in
# config.yml, so this axis owns the whole ~/.config/lazydocker/config.yml as a
# managed render (config.yml is deliberately NOT in the bundle manifest). Palette is
# poor — lazydocker exposes only four theme roles. NOT live (next invocation).
# Band 500 = terminal/CLI.
DESC="lazydocker container TUI theme"

LAZYDOCKER_REL=".config/lazydocker/config.yml"

render_user() {
  load_conf "$(w_userscope_theme_dir)"
  echo "w-style: rendering lazydocker theme..."

  # YAML: brand colours start with '#', so each must be single-quoted or YAML reads
  # it as a comment. gui.theme values are lists of strings (colour and/or attribute).
  write_user_file "$LAZYDOCKER_REL" <<EOF
# W Linux — generated by w-style. Do not edit; theme comes from the active theme's
# theme.conf. This axis owns the whole file (lazydocker has no external theme file).
gui:
  theme:
    activeBorderColor:
      - '$W_PRIMARY'
      - bold
    inactiveBorderColor:
      - '$W_ON_SURFACE_VARIANT'
    selectedLineBgColor:
      - '$W_PRIMARY_CONTAINER'
    optionsTextColor:
      - '$W_PRIMARY'
EOF

  echo "w-style: lazydocker done (applies to the next lazydocker invocation)."
}
