# w-style module: btop (user-scope) — monitor theme (Tier-2 roles; gradients
# container→primary→error). btop.conf (skel) selects color_theme "w"; btop reads
# the theme at startup, a running btop via its in-app theme reload. NOT live
# (next invocation). Band 500 = terminal/CLI.
DESC="btop monitor theme (TUI)"

BTOP_THEME_REL=".config/btop/themes/w.theme"

render_user() {
  load_conf "$(w_userscope_theme_dir)"
  echo "w-style: rendering btop theme..."

  write_user_file "$BTOP_THEME_REL" <<EOF
# W Linux — generated by w-style. Do not edit; edit the theme's theme.conf.
theme[main_bg]="$W_APP_BG"
theme[main_fg]="$W_ON_SURFACE"
theme[title]="$W_ON_SURFACE"
theme[hi_fg]="$W_PRIMARY"
theme[selected_bg]="$W_PRIMARY_CONTAINER"
theme[selected_fg]="$W_ON_PRIMARY_CONTAINER"
theme[inactive_fg]="$W_ON_SURFACE_VARIANT"
theme[graph_text]="$W_ON_SURFACE_VARIANT"
theme[meter_bg]="$W_SURFACE"
theme[proc_misc]="$W_PRIMARY"
theme[cpu_box]="$W_ON_SURFACE_VARIANT"
theme[mem_box]="$W_ON_SURFACE_VARIANT"
theme[net_box]="$W_ON_SURFACE_VARIANT"
theme[proc_box]="$W_ON_SURFACE_VARIANT"
theme[div_line]="$W_SURFACE_VARIANT"
theme[temp_start]="$W_PRIMARY"
theme[temp_mid]="$W_ON_ERROR_CONTAINER"
theme[temp_end]="$W_ERROR"
theme[cpu_start]="$W_PRIMARY_CONTAINER"
theme[cpu_mid]="$W_PRIMARY"
theme[cpu_end]="$W_ERROR"
theme[free_start]="$W_PRIMARY_CONTAINER"
theme[free_mid]="$W_PRIMARY"
theme[free_end]="$W_PRIMARY"
theme[cached_start]="$W_PRIMARY"
theme[cached_mid]="$W_PRIMARY"
theme[cached_end]="$W_ON_ERROR_CONTAINER"
theme[available_start]="$W_PRIMARY_CONTAINER"
theme[available_mid]="$W_PRIMARY"
theme[available_end]="$W_PRIMARY"
theme[used_start]="$W_PRIMARY"
theme[used_mid]="$W_ON_ERROR_CONTAINER"
theme[used_end]="$W_ERROR"
theme[download_start]="$W_PRIMARY_CONTAINER"
theme[download_mid]="$W_PRIMARY"
theme[download_end]="$W_ERROR"
theme[upload_start]="$W_PRIMARY_CONTAINER"
theme[upload_mid]="$W_PRIMARY"
theme[upload_end]="$W_ERROR"
theme[process_start]="$W_PRIMARY_CONTAINER"
theme[process_mid]="$W_PRIMARY"
theme[process_end]="$W_ERROR"
EOF

  echo "w-style: btop done (applies to the next btop invocation)."
}
