# w-style module: micro (user-scope) — terminal editor colorscheme. settings.json
# (skel) selects colorscheme "w"; micro reads the scheme at startup / on
# `set colorscheme`, so this is NOT live (next invocation), like btop/atuin/yazi.
# No new theme tokens: micro's highlight groups map onto existing Tier-2 roles +
# the Tier-3 terminal ANSI pigments (W_TERM_ANSI_*), like the other TUI axes.
# Format: `color-link <group> "<fg>,<bg>"` (either side may be empty), truecolor
# hex, optional bold/italic/underline prefix. Band 500 = terminal/CLI.
DESC="micro editor colorscheme (TUI)"

MICRO_SCHEME_REL=".config/micro/colorschemes/w.micro"

render_user() {
  load_conf "$(w_userscope_theme_dir)"
  echo "w-style: rendering micro colorscheme..."

  write_user_file "$MICRO_SCHEME_REL" <<EOF
# W Linux — generated by w-style. Do not edit; edit the theme's theme.conf.
# Editor base
color-link default "$W_TERM_FG,$W_TERM_BG"
color-link comment "italic $W_ON_SURFACE_VARIANT"
color-link comment.bright "italic $W_ON_SURFACE"

# Identifiers / functions / macros
color-link identifier "$W_TERM_FG"
color-link identifier.class "$W_TERM_ANSI_BLUE"
color-link identifier.macro "$W_TERM_ANSI_BRIGHT_CYAN"
color-link identifier.var "$W_TERM_FG"

# Constants
color-link constant "$W_TERM_ANSI_CYAN"
color-link constant.bool "$W_TERM_ANSI_YELLOW"
color-link constant.number "$W_TERM_ANSI_BRIGHT_MAGENTA"
color-link constant.string "$W_TERM_ANSI_GREEN"
color-link constant.string.url "underline $W_TERM_ANSI_GREEN"
color-link constant.specialChar "$W_TERM_ANSI_BRIGHT_MAGENTA"

# Keywords / statements / types
color-link statement "$W_PRIMARY"
color-link type "$W_TERM_ANSI_BRIGHT_CYAN"
color-link type.keyword "$W_PRIMARY"
color-link special "$W_TERM_ANSI_RED"
color-link preproc "$W_TERM_ANSI_YELLOW"
color-link preproc.shebang "italic $W_ON_SURFACE_VARIANT"

# Symbols
color-link symbol "$W_ON_SURFACE"
color-link symbol.brackets "$W_ON_SURFACE_VARIANT"
color-link symbol.operator "$W_ON_SURFACE_VARIANT"
color-link symbol.tag "$W_TERM_ANSI_RED"

# Misc text
color-link underlined "underline $W_TERM_ANSI_BLUE"
color-link error "bold $W_ON_ERROR,$W_ERROR"
color-link todo "bold $W_TERM_ANSI_YELLOW"
color-link selection "$W_TERM_SELECTION_FG,$W_TERM_SELECTION_BG"

# Gutter / line numbers / current line
color-link line-number "$W_ON_SURFACE_VARIANT,$W_APP_BG"
color-link current-line-number "bold $W_PRIMARY,$W_APP_BG"
# micro reads cursor-line / color-column / trailingws via the style's FOREGROUND
# and paints it as the line/cell background (Decompose→Background(fg)), so the
# highlight hue goes in the fg slot (single value), not the bg slot.
color-link cursor-line "$W_SURFACE_DIM"
color-link color-column "$W_SURFACE"
color-link gutter-info "$W_TERM_ANSI_BLUE"
color-link gutter-warning "$W_TERM_ANSI_YELLOW"
color-link gutter-error "$W_ERROR"

# Statusline / tabbar
color-link statusline "$W_ON_SURFACE,$W_SURFACE_VARIANT"
color-link statusline.inactive "$W_ON_SURFACE_VARIANT,$W_SURFACE"
color-link statusline.suggestions "$W_ON_SURFACE,$W_SURFACE"
color-link tabbar "$W_ON_SURFACE_VARIANT,$W_SURFACE"
color-link tabbar.active "$W_ON_PRIMARY_CONTAINER,$W_PRIMARY_CONTAINER"

# Diff gutter
color-link diff-added "$W_TERM_ANSI_GREEN"
color-link diff-modified "$W_TERM_ANSI_YELLOW"
color-link diff-deleted "$W_TERM_ANSI_RED"

# Chrome
color-link match-brace "$W_ON_PRIMARY_CONTAINER,$W_PRIMARY_CONTAINER"
color-link divider "$W_PRIMARY,$W_SURFACE"
color-link scrollbar "$W_PRIMARY"
color-link message "$W_ON_SURFACE"
color-link error-message "$W_ON_ERROR,$W_ERROR"
color-link hlsearch "$W_ON_PRIMARY_CONTAINER,$W_PRIMARY_CONTAINER"
color-link trailingws "$W_ERROR"
color-link indent-char "$W_ON_SURFACE_VARIANT"
EOF

  echo "w-style: micro done (applies to the next micro invocation)."
}
