# w-style module: shell (user-scope) — CLI/prompt colors for the zsh stack.
# ANSI-first: syntax highlighting, fzf and the prompt ride the ghostty ANSI palette
# (W_TERM_*), so a theme switch recolors them for free and they stay sane over
# SSH/in a TTY. Only the signature accents are exact brand hex: the directory hue
# (shared W_DIR_HUE — LS_COLORS `di`, zsh path style, Starship dir segment) and the
# prompt/git/error accents. Two outputs: ~/.config/w/shell-colors.zsh (sourced by
# .zshrc) and the [palettes.w] marker region inside ~/.config/starship.toml (layout
# stays static in skel). NOT live: a new shell / `source ~/.zshrc` picks it up.
# Band 500 = terminal / CLI / TUI surfaces.
DESC="CLI/prompt colors (zsh stack + Starship)"

SHELL_COLORS_REL=".config/w/shell-colors.zsh"   # LS_COLORS/zsh/fzf/eza/jq colors
STARSHIP_CONFIG_REL=".config/starship.toml"     # Starship [palettes.w] region

# LS_COLORS / SGR truecolor foreground spec from #rrggbb → "38;2;r;g;b".
hex_to_ansi_fg() { local h="${1#\#}"; printf '38;2;%d;%d;%d' "0x${h:0:2}" "0x${h:2:2}" "0x${h:4:2}"; }

# Replace the inner content between "# >>> $tag" and "# <<< $tag" marker lines in a
# user-scope file (markers preserved), writing new content from stdin. Renders the
# Starship [palettes.w] block inside the static skel starship.toml. No-op if the
# file or markers are absent (skel ships them).
write_marked_region() {
  local rel="$1" tag="$2" target inner
  inner="$(cat)"
  if [[ $EUID -eq 0 ]]; then target="/etc/skel/$rel"; else target="$HOME/$rel"; fi
  [[ -f "$target" ]] || return 0
  # Match lines that START with the marker (the begin marker may carry a trailing
  # "(generated …)" comment) — full-line equality would miss it. The replacement
  # rides stdin (first input, NR==FNR), not an awk -v var: BSD awk rejects
  # newlines in -v assignments ("newline in string"), and the unit tests run
  # this on macOS.
  printf '%s\n' "$inner" | awk -v b="# >>> $tag" -v e="# <<< $tag" '
    NR == FNR { repl[NR] = $0; n = NR; next }
    index($0, b) == 1 { print; for (i = 1; i <= n; i++) print repl[i]; skip=1; next }
    index($0, e) == 1 { skip=0 }
    !skip { print }
  ' - "$target" >"$target.tmp" && mv "$target.tmp" "$target"
}

render_user() {
  load_conf "$(w_userscope_theme_dir)"
  echo "w-style: rendering shell colors..."

  # Truecolor SGR sequences for LS_COLORS / EZA_COLORS / JQ_COLORS (numeric SGR,
  # not hex — these consumers want escape codes, while zsh/fzf take hex directly).
  local di ln ex pi so str kw err
  di="$(hex_to_ansi_fg "$W_SHELL_DIR")"
  ln="$(hex_to_ansi_fg "$W_SHELL_ACCENT")"
  ex="$(hex_to_ansi_fg "$W_SHELL_CMD")"
  pi="$(hex_to_ansi_fg "$W_SHELL_MUTED")"
  so="$(hex_to_ansi_fg "$W_SHELL_NUMBER")"
  str="$(hex_to_ansi_fg "$W_SHELL_STRING")"
  kw="$(hex_to_ansi_fg "$W_SHELL_KEYWORD")"
  err="$(hex_to_ansi_fg "$W_SHELL_ERROR")"

  write_user_file "$SHELL_COLORS_REL" <<EOF
# W Linux — generated by w-style. Do not edit; edit the theme's theme.conf.
# Sourced by ~/.zshrc (and re-sourced live by its precmd hook on theme switch).
# W-Terminal is GUI/truecolor-first: exact theme hex, not ANSI roles.

# LS_COLORS: GNU default database, then brand directory/link/exec/socket hues
# (the trailing entries win — GNU ls/eza use the last match).
eval "\$(dircolors -b 2>/dev/null)"
export LS_COLORS="\${LS_COLORS}di=${di}:ln=${ln}:ex=${ex};1:pi=${pi}:so=${so}:bd=${pi}:cd=${pi}:or=${ex}:"

# zsh-syntax-highlighting — exact theme hex per syntactic role.
typeset -gA ZSH_HIGHLIGHT_STYLES
ZSH_HIGHLIGHT_STYLES[default]='none'
ZSH_HIGHLIGHT_STYLES[unknown-token]='fg=${W_SHELL_ERROR},bold'
ZSH_HIGHLIGHT_STYLES[reserved-word]='fg=${W_SHELL_KEYWORD}'
ZSH_HIGHLIGHT_STYLES[alias]='fg=${W_SHELL_CMD},bold'
ZSH_HIGHLIGHT_STYLES[suffix-alias]='fg=${W_SHELL_CMD},bold'
ZSH_HIGHLIGHT_STYLES[global-alias]='fg=${W_SHELL_CMD},bold'
ZSH_HIGHLIGHT_STYLES[builtin]='fg=${W_SHELL_CMD},bold'
ZSH_HIGHLIGHT_STYLES[function]='fg=${W_SHELL_FUNCTION},bold'
ZSH_HIGHLIGHT_STYLES[command]='fg=${W_SHELL_CMD},bold'
ZSH_HIGHLIGHT_STYLES[precommand]='fg=${W_SHELL_CMD},bold,underline'
ZSH_HIGHLIGHT_STYLES[hashed-command]='fg=${W_SHELL_CMD},bold'
ZSH_HIGHLIGHT_STYLES[arg0]='fg=${W_SHELL_CMD}'
ZSH_HIGHLIGHT_STYLES[commandseparator]='fg=${W_SHELL_OPERATOR}'
ZSH_HIGHLIGHT_STYLES[redirection]='fg=${W_SHELL_OPERATOR}'
ZSH_HIGHLIGHT_STYLES[named-fd]='fg=${W_SHELL_OPERATOR}'
ZSH_HIGHLIGHT_STYLES[numeric-fd]='fg=${W_SHELL_OPERATOR}'
ZSH_HIGHLIGHT_STYLES[path]='fg=${W_SHELL_DIR}'
ZSH_HIGHLIGHT_STYLES[path_prefix]='fg=${W_SHELL_DIR}'
ZSH_HIGHLIGHT_STYLES[path_pathseparator]='fg=${W_SHELL_OPERATOR}'
ZSH_HIGHLIGHT_STYLES[path_prefix_pathseparator]='fg=${W_SHELL_OPERATOR}'
ZSH_HIGHLIGHT_STYLES[assign]='fg=${W_SHELL_DIR}'
ZSH_HIGHLIGHT_STYLES[globbing]='fg=${W_SHELL_NUMBER}'
ZSH_HIGHLIGHT_STYLES[history-expansion]='fg=${W_SHELL_NUMBER}'
ZSH_HIGHLIGHT_STYLES[single-hyphen-option]='fg=${W_SHELL_OPTION}'
ZSH_HIGHLIGHT_STYLES[double-hyphen-option]='fg=${W_SHELL_OPTION}'
ZSH_HIGHLIGHT_STYLES[single-quoted-argument]='fg=${W_SHELL_STRING}'
ZSH_HIGHLIGHT_STYLES[double-quoted-argument]='fg=${W_SHELL_STRING}'
ZSH_HIGHLIGHT_STYLES[dollar-quoted-argument]='fg=${W_SHELL_STRING}'
ZSH_HIGHLIGHT_STYLES[back-quoted-argument]='fg=${W_SHELL_STRING}'
ZSH_HIGHLIGHT_STYLES[dollar-double-quoted-argument]='fg=${W_SHELL_NUMBER}'
ZSH_HIGHLIGHT_STYLES[comment]='fg=${W_SHELL_COMMENT},italic'

# zsh-autosuggestions — muted exact hex.
export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=${W_SHELL_MUTED}'

# fzf — truecolor hex from the theme (rounded border, reverse layout).
export FZF_DEFAULT_OPTS="--height=45% --layout=reverse --border=rounded --color=hl:${W_SHELL_CMD},fg+:${W_SHELL_ACCENT},hl+:${W_SHELL_CMD},info:${W_SHELL_MUTED},prompt:${W_SHELL_ACCENT},pointer:${W_SHELL_ACCENT},marker:${W_SHELL_NUMBER},spinner:${W_SHELL_ACCENT},border:${W_SHELL_MUTED},header:${W_SHELL_MUTED}"

# eza — truecolor listing (extends LS_COLORS with eza fields: dates, owners,
# sizes, git status). bat follows the live ghostty palette via BAT_THEME=ansi.
export EZA_COLORS="di=${di}:ex=${ex};1:ln=${ln}:da=${pi}:uu=${str}:gu=${pi}:sn=${so}:sb=${pi}:ga=${ex}:gm=${kw}:gd=${err}:gv=${so}:xx=${pi}:hd=${pi}"

# jq — null:false:true:numbers:strings:arrays:objects:object-keys (SGR codes).
export JQ_COLORS="${pi}:${err}:${ex}:${so}:${str}:${di}:${di}:${ln}"
EOF

  # Starship [palettes.w] — only the marked region; the prompt layout is static skel.
  write_marked_region "$STARSHIP_CONFIG_REL" "W palette" <<EOF
[palettes.w]
accent = "$W_SHELL_ACCENT"
cmd = "$W_SHELL_CMD"
dir = "$W_SHELL_DIR"
git = "$W_SHELL_GIT"
string = "$W_SHELL_STRING"
muted = "$W_SHELL_MUTED"
error = "$W_SHELL_ERROR"
EOF

  echo "w-style: shell done (open terminals recolor live via the .zshrc precmd hook)."
}
