# w-style module: greeter (system-scope) — the Quickshell login shell's
# core/{colors,motion,font,geometry,effects}.json, rendered from the system-fallback
# theme. Byte-compatible with the user shell's render (the quickshell/motion/font/
# geometry/effects axes), so the greeter and the desktop share one look. Not live:
# the greeter reads fresh files each login (no running instance to signal). Plain
# `cat` (root-owned, read-only /etc) — no inode-watch concerns like the user shell.
# Band 900 = system-scope surfaces.
DESC="Quickshell greeter design-system (colors+motion+font+geometry+effects)"

# The login shell's design-system JSON dir (system-scope), rendered from the
# system-fallback theme — the same contract as the user shell's core/*.json.
GREETER_QS_CORE="/etc/greetd/quickshell/w/core"

render_system() {
  require_root "apply greeter"
  echo "w-style: rendering Quickshell greeter (colors + motion + font + geometry + effects)..."

  [[ -d "$GREETER_QS_CORE" ]] \
    || { echo "w-style: greeter config dir not found ($GREETER_QS_CORE) — is the greeter deployed?" >&2; exit 1; }

  load_conf "$(w_system_theme_dir)"
  cat > "$GREETER_QS_CORE/colors.json" <<EOF
{
  "_comment": "W Linux — generated by w-style (apply greeter). Do not edit; edit the system theme's theme.conf.",
  "backdrop": "$W_QS_BACKDROP",
  "surface":  "$W_QS_SURFACE",
  "inputBg":  "$W_QS_INPUT_BG",
  "text":     "$W_QS_TEXT",
  "muted":    "$W_QS_MUTED",
  "accent":   "$W_QS_ACCENT",
  "accentFg": "$W_QS_ACCENT_FG",
  "border":   "$W_QS_BORDER",
  "iconTint": "$W_QS_ICON_TINT",
  "dangerBg":     "$W_QS_DANGER_BG",
  "dangerFg":     "$W_QS_DANGER_FG",
  "dangerBorder": "$W_QS_DANGER_BORDER"
}
EOF

  load_motion "$(resolve_theme_file "$(w_system_theme_dir)" motion.conf)"
  cat > "$GREETER_QS_CORE/motion.json" <<EOF
{
  "_comment": "W Linux — generated by w-style (apply greeter). Do not edit; edit the system theme's motion.conf (default /etc/w/themes/w/motion.conf).",
  "fast": $W_MOTION_FAST,
  "base": $W_MOTION_BASE,
  "slow": $W_MOTION_SLOW,
  "bezier": [$W_MOTION_BEZIER]
}
EOF

  load_font "$(resolve_theme_file "$(w_system_theme_dir)" font.conf)"
  cat > "$GREETER_QS_CORE/font.json" <<EOF
{
  "_comment": "W Linux — generated by w-style (apply greeter). Do not edit; edit the system theme's font.conf.",
  "ui":       "${W_FONT_UI}",
  "mono":     "${W_FONT_MONO}",
  "uiSize":   ${W_FONT_UI_SIZE},
  "monoSize": ${W_FONT_MONO_SIZE}
}
EOF

  load_geometry "$(resolve_theme_file "$(w_system_theme_dir)" geometry.conf)"
  cat > "$GREETER_QS_CORE/geometry.json" <<EOF
{
  "_comment": "W Linux — generated by w-style (apply greeter). Do not edit; edit the system theme's geometry.conf (default /etc/w/themes/w/geometry.conf).",
  "radius": $W_GEO_RADIUS,
  "radiusSm": $W_GEO_RADIUS_SM,
  "padding": $W_GEO_PADDING,
  "gap": $W_GEO_GAP,
  "border": $W_GEO_BORDER
}
EOF

  load_effects "$(resolve_theme_file "$(w_system_theme_dir)" effects.conf)"
  cat > "$GREETER_QS_CORE/effects.json" <<EOF
{
  "_comment": "W Linux — generated by w-style (apply greeter). Do not edit; edit the system theme's effects.conf (default /etc/w/themes/w/effects.conf).",
  "surfaceOpacity": $W_FX_SURFACE_OPACITY,
  "scrimOpacity": $W_FX_SCRIM_OPACITY
}
EOF

  echo "w-style: greeter done (takes effect on next login)."
}
