# w-style module: zed (user-scope) — GUI code editor theme.
#
# Ships INSIDE the dev W-Pack (source of truth); `w-pack install dev` drops this
# axis into the w-style modules.d drop-in root and renders it. Core w-style carries
# no reference to Zed → the axis exists iff the bundle is installed, so no
# presence-guard is needed (packs.md "bundle self-containment", pack-dev.md).
#
# Zed is neither GTK nor Qt (own GPU toolkit, GPUI), so the `gtk`/`qt` axes do not
# reach it — it needs this dedicated axis. Ownership split mirrors helix/micro:
# ~/.config/zed/settings.json is the USER's (seeded once by the bundle manifest,
# selects theme "W"), while the theme file below is fully W-owned and re-rendered
# on every theme switch.
#
# LIVE (verified on the reference machine): Zed watches its themes directory and
# recolours a RUNNING editor on `w-theme set` — no restart. This depends on
# write_user_file rewriting the file IN PLACE (same inode → a plain IN_MODIFY); do
# not switch this axis to write_user_file_atomic, which unlinks and replaces the
# file. Band 400 = GUI applications (next to firefox/satty).
#
# No new theme tokens: Zed's UI roles map onto the existing Tier-2 semantic roles
# and its editor/terminal colours onto the Tier-3 terminal pigments (W_TERM_*),
# exactly like the helix axis — one theme.conf recolours CLI and GUI editors alike.
DESC="zed editor theme (GUI)"

ZED_THEME_REL=".config/zed/themes/w.json"

# 0..1 opacity → two hex digits, for Zed's #rrggbbaa colour strings.
zed_alpha_hex() {
  awk -v o="${1:-1}" 'BEGIN { if (o > 1) o = 1; if (o < 0) o = 0; printf "%02x", int(o * 255 + 0.5) }'
}

render_user() {
  local theme_dir; theme_dir="$(w_userscope_theme_dir)"
  load_conf "$theme_dir"
  load_effects "$(resolve_theme_file "$theme_dir" effects.conf)"
  echo "w-style: rendering zed theme..."

  # App-background translucency (effects axis, concept ③ "app-bg translucency"):
  # the same knob Ghostty/GTK/Qt honour. When it is below 1 the window chrome and
  # editor surfaces get an alpha channel and the window is declared "blurred", so
  # Hyprland's blur frosts Zed like every other W surface. Popovers, modals and
  # elevated surfaces stay opaque — legibility beats consistency for floating text.
  #
  # The "blurred" declaration below only reaches a window that is CREATED with this
  # theme already registered — and a user theme is registered by a background task,
  # so a cold start can beat it and be born opaque (no blur until the next settings
  # write). The bundle's settings.json therefore pins the surface mode a second time
  # via `experimental.theme_overrides`; the colours here stay the single source.
  local alpha="" window_bg="opaque"
  if awk -v o="${W_FX_APP_BG_OPACITY:-1}" 'BEGIN { exit !(o < 1) }'; then
    alpha="$(zed_alpha_hex "$W_FX_APP_BG_OPACITY")"
    window_bg="blurred"
  fi

  write_user_file "$ZED_THEME_REL" <<EOF
{
  "\$schema": "https://zed.dev/schema/themes/v0.2.0.json",
  "name": "W",
  "author": "W Linux (generated by w-style — do not edit; edit the theme's theme.conf)",
  "themes": [
    {
      "name": "W",
      "appearance": "$W_APPEARANCE",
      "style": {
        "background.appearance": "$window_bg",
        "background": "$W_APP_BG$alpha",
        "surface.background": "$W_SURFACE",
        "elevated_surface.background": "$W_SURFACE_VARIANT",

        "border": "$W_SURFACE_VARIANT",
        "border.variant": "$W_SURFACE",
        "border.focused": "$W_PRIMARY",
        "border.selected": "$W_PRIMARY",
        "border.disabled": "$W_SURFACE",
        "border.transparent": "#00000000",

        "element.background": "$W_SURFACE_VARIANT",
        "element.hover": "$W_SURFACE_VARIANT",
        "element.active": "$W_PRIMARY_CONTAINER",
        "element.selected": "$W_PRIMARY_CONTAINER",
        "element.disabled": "$W_SURFACE_DIM",
        "ghost_element.background": "#00000000",
        "ghost_element.hover": "$W_SURFACE_VARIANT",
        "ghost_element.active": "$W_PRIMARY_CONTAINER",
        "ghost_element.selected": "$W_PRIMARY_CONTAINER",
        "ghost_element.disabled": "$W_SURFACE_DIM",
        "drop_target.background": "$W_PRIMARY_CONTAINER",

        "text": "$W_ON_SURFACE",
        "text.muted": "$W_ON_SURFACE_VARIANT",
        "text.placeholder": "$W_ON_SURFACE_VARIANT",
        "text.disabled": "$W_ON_SURFACE_VARIANT",
        "text.accent": "$W_PRIMARY",
        "link_text.hover": "$W_PRIMARY",
        "icon": "$W_ON_SURFACE",
        "icon.muted": "$W_ON_SURFACE_VARIANT",
        "icon.disabled": "$W_ON_SURFACE_VARIANT",
        "icon.placeholder": "$W_ON_SURFACE_VARIANT",
        "icon.accent": "$W_PRIMARY",

        "title_bar.background": "$W_SURFACE$alpha",
        "title_bar.inactive_background": "$W_SURFACE_DIM$alpha",
        "status_bar.background": "$W_SURFACE$alpha",
        "toolbar.background": "$W_APP_BG$alpha",
        "tab_bar.background": "$W_SURFACE_DIM$alpha",
        "tab.active_background": "$W_APP_BG$alpha",
        "tab.inactive_background": "$W_SURFACE_DIM$alpha",
        "panel.background": "$W_SURFACE$alpha",
        "panel.focused_border": "$W_PRIMARY",
        "panel.indent_guide": "$W_SURFACE_VARIANT",
        "panel.indent_guide_active": "$W_PRIMARY",
        "panel.indent_guide_hover": "$W_PRIMARY",
        "pane.focused_border": "$W_PRIMARY",
        "pane_group.border": "$W_SURFACE_VARIANT",

        "editor.background": "$W_APP_BG$alpha",
        "editor.foreground": "$W_TERM_FG",
        "editor.gutter.background": "$W_APP_BG$alpha",
        "editor.subheader.background": "$W_SURFACE$alpha",
        "editor.active_line.background": "$W_SURFACE_DIM$alpha",
        "editor.highlighted_line.background": "$W_SURFACE",
        "editor.line_number": "$W_ON_SURFACE_VARIANT",
        "editor.active_line_number": "$W_PRIMARY",
        "editor.invisible": "$W_ON_SURFACE_VARIANT",
        "editor.wrap_guide": "$W_SURFACE",
        "editor.active_wrap_guide": "$W_SURFACE_VARIANT",
        "editor.indent_guide": "$W_SURFACE",
        "editor.indent_guide_active": "$W_PRIMARY",
        "editor.document_highlight.read_background": "$W_SURFACE_VARIANT",
        "editor.document_highlight.write_background": "$W_PRIMARY_CONTAINER",
        "editor.document_highlight.bracket_background": "$W_PRIMARY_CONTAINER",
        "search.match_background": "$W_PRIMARY_CONTAINER",

        "scrollbar.track.background": "#00000000",
        "scrollbar.track.border": "#00000000",
        "scrollbar.thumb.background": "$W_PRIMARY_CONTAINER",
        "scrollbar.thumb.hover_background": "$W_PRIMARY",
        "scrollbar.thumb.border": "#00000000",

        "error": "$W_ERROR",
        "error.background": "$W_DANGER_CONTAINER",
        "error.border": "$W_ERROR",
        "warning": "$W_TERM_ANSI_YELLOW",
        "warning.background": "$W_SURFACE",
        "warning.border": "$W_TERM_ANSI_YELLOW",
        "info": "$W_TERM_ANSI_BLUE",
        "info.background": "$W_SURFACE",
        "info.border": "$W_TERM_ANSI_BLUE",
        "hint": "$W_TERM_ANSI_CYAN",
        "hint.background": "$W_SURFACE",
        "hint.border": "$W_TERM_ANSI_CYAN",
        "success": "$W_TERM_ANSI_GREEN",
        "success.background": "$W_SURFACE",
        "success.border": "$W_TERM_ANSI_GREEN",
        "predictive": "$W_ON_SURFACE_VARIANT",
        "predictive.background": "$W_SURFACE",
        "predictive.border": "$W_ON_SURFACE_VARIANT",

        "created": "$W_TERM_ANSI_GREEN",
        "created.background": "$W_SURFACE",
        "created.border": "$W_TERM_ANSI_GREEN",
        "modified": "$W_TERM_ANSI_YELLOW",
        "modified.background": "$W_SURFACE",
        "modified.border": "$W_TERM_ANSI_YELLOW",
        "deleted": "$W_TERM_ANSI_RED",
        "deleted.background": "$W_SURFACE",
        "deleted.border": "$W_TERM_ANSI_RED",
        "renamed": "$W_TERM_ANSI_BLUE",
        "renamed.background": "$W_SURFACE",
        "renamed.border": "$W_TERM_ANSI_BLUE",
        "conflict": "$W_DANGER",
        "conflict.background": "$W_DANGER_CONTAINER",
        "conflict.border": "$W_DANGER",
        "ignored": "$W_ON_SURFACE_VARIANT",
        "ignored.background": "$W_SURFACE",
        "ignored.border": "$W_ON_SURFACE_VARIANT",
        "hidden": "$W_ON_SURFACE_VARIANT",
        "hidden.background": "$W_SURFACE",
        "hidden.border": "$W_ON_SURFACE_VARIANT",
        "unreachable": "$W_ON_SURFACE_VARIANT",
        "unreachable.background": "$W_SURFACE",
        "unreachable.border": "$W_ON_SURFACE_VARIANT",

        "terminal.background": "$W_TERM_BG$alpha",
        "terminal.foreground": "$W_TERM_FG",
        "terminal.bright_foreground": "$W_TERM_ANSI_BRIGHT_WHITE",
        "terminal.dim_foreground": "$W_ON_SURFACE_VARIANT",
        "terminal.ansi.background": "$W_TERM_BG",
        "terminal.ansi.black": "$W_TERM_ANSI_BLACK",
        "terminal.ansi.red": "$W_TERM_ANSI_RED",
        "terminal.ansi.green": "$W_TERM_ANSI_GREEN",
        "terminal.ansi.yellow": "$W_TERM_ANSI_YELLOW",
        "terminal.ansi.blue": "$W_TERM_ANSI_BLUE",
        "terminal.ansi.magenta": "$W_TERM_ANSI_MAGENTA",
        "terminal.ansi.cyan": "$W_TERM_ANSI_CYAN",
        "terminal.ansi.white": "$W_TERM_ANSI_WHITE",
        "terminal.ansi.bright_black": "$W_TERM_ANSI_BRIGHT_BLACK",
        "terminal.ansi.bright_red": "$W_TERM_ANSI_BRIGHT_RED",
        "terminal.ansi.bright_green": "$W_TERM_ANSI_BRIGHT_GREEN",
        "terminal.ansi.bright_yellow": "$W_TERM_ANSI_BRIGHT_YELLOW",
        "terminal.ansi.bright_blue": "$W_TERM_ANSI_BRIGHT_BLUE",
        "terminal.ansi.bright_magenta": "$W_TERM_ANSI_BRIGHT_MAGENTA",
        "terminal.ansi.bright_cyan": "$W_TERM_ANSI_BRIGHT_CYAN",
        "terminal.ansi.bright_white": "$W_TERM_ANSI_BRIGHT_WHITE",

        "players": [
          {
            "cursor": "$W_TERM_CURSOR",
            "background": "$W_PRIMARY",
            "selection": "$W_PRIMARY_CONTAINER"
          }
        ],
        "accents": ["$W_PRIMARY", "$W_ERROR", "$W_TERM_ANSI_CYAN"],

        "syntax": {
          "comment": { "color": "$W_ON_SURFACE_VARIANT", "font_style": "italic" },
          "comment.doc": { "color": "$W_ON_SURFACE_VARIANT", "font_style": "italic" },
          "string": { "color": "$W_TERM_ANSI_GREEN" },
          "string.special": { "color": "$W_TERM_ANSI_BRIGHT_CYAN" },
          "string.special.symbol": { "color": "$W_TERM_ANSI_BRIGHT_CYAN" },
          "string.escape": { "color": "$W_TERM_ANSI_BRIGHT_MAGENTA" },
          "string.regex": { "color": "$W_TERM_ANSI_BRIGHT_CYAN" },
          "constant": { "color": "$W_TERM_ANSI_CYAN" },
          "number": { "color": "$W_TERM_ANSI_BRIGHT_MAGENTA" },
          "boolean": { "color": "$W_TERM_ANSI_CYAN" },
          "keyword": { "color": "$W_PRIMARY" },
          "operator": { "color": "$W_ON_SURFACE_VARIANT" },
          "punctuation": { "color": "$W_ON_SURFACE_VARIANT" },
          "punctuation.bracket": { "color": "$W_ON_SURFACE_VARIANT" },
          "punctuation.delimiter": { "color": "$W_ON_SURFACE_VARIANT" },
          "punctuation.special": { "color": "$W_TERM_ANSI_RED" },
          "punctuation.list_marker": { "color": "$W_PRIMARY" },
          "function": { "color": "$W_TERM_ANSI_BLUE" },
          "function.method": { "color": "$W_TERM_ANSI_BLUE" },
          "function.builtin": { "color": "$W_TERM_ANSI_BRIGHT_BLUE" },
          "function.definition": { "color": "$W_TERM_ANSI_BLUE" },
          "type": { "color": "$W_TERM_ANSI_BRIGHT_CYAN" },
          "type.builtin": { "color": "$W_PRIMARY" },
          "constructor": { "color": "$W_TERM_ANSI_BRIGHT_CYAN" },
          "enum": { "color": "$W_TERM_ANSI_CYAN" },
          "variable": { "color": "$W_TERM_FG" },
          "variable.special": { "color": "$W_TERM_ANSI_RED" },
          "variable.parameter": { "color": "$W_ON_SURFACE" },
          "property": { "color": "$W_ON_SURFACE" },
          "attribute": { "color": "$W_TERM_ANSI_YELLOW" },
          "tag": { "color": "$W_TERM_ANSI_RED" },
          "label": { "color": "$W_TERM_ANSI_YELLOW" },
          "namespace": { "color": "$W_TERM_ANSI_BRIGHT_CYAN" },
          "preproc": { "color": "$W_TERM_ANSI_BRIGHT_MAGENTA" },
          "embedded": { "color": "$W_ON_SURFACE" },
          "primary": { "color": "$W_ON_SURFACE" },
          "predictive": { "color": "$W_ON_SURFACE_VARIANT", "font_style": "italic" },
          "hint": { "color": "$W_TERM_ANSI_CYAN" },
          "emphasis": { "color": "$W_PRIMARY", "font_style": "italic" },
          "emphasis.strong": { "color": "$W_PRIMARY", "font_weight": 700 },
          "title": { "color": "$W_PRIMARY", "font_weight": 700 },
          "link_text": { "color": "$W_TERM_ANSI_CYAN", "font_style": "italic" },
          "link_uri": { "color": "$W_TERM_ANSI_GREEN" }
        }
      }
    }
  ]
}
EOF

  echo "w-style: zed done (live — a running Zed recolours itself)."
}
