# check/i18n.sh — localization completeness + steps.conf references.
#
# Three surfaces, three failure modes this catches before a VM run:
#   1. TUI dicts (install/i18n/*.conf): a key added to en but not ru renders
#      as a raw key name mid-install. (Checked on the GENERATED files on
#      purpose — belt and braces over rule 0, and the assertion the consumer
#      actually depends on.)
#   2. steps.conf: a title/prompt i18n key or an options/validate/condition
#      function that doesn't exist fails only when the wizard reaches that row.
#   3. Quickshell (shell + greeter trees): Strings.t("x") with a key missing
#      from that tree's core/i18n.json (or missing a language) shows raw keys
#      in the UI. Only literal calls are checkable — dynamic ones (2 known,
#      Hub panel titles) are registered elsewhere and resolve at runtime,
#      which is also why unused-key detection is informational, not gating.

_i18n_keys() { grep -oE '^[A-Za-z_][A-Za-z0-9_]*=' "$1" | sed 's/=$//' | sort; }

chk_i18n() {
  local rc=0 base="scripts/install/i18n"

  # 0. The golden gate. Every dictionary in the tree is GENERATED from i18n/ by
  #    w-i18n-gen — the shell's and the greeter's core/i18n.json, the installer's
  #    dicts, /usr/share/w/i18n for the scripts, and the localized keys inside our
  #    .desktop files. Regenerating must be a no-op, so a hand-edit of a generated
  #    file is red here instead of being quietly overwritten by the next run. It
  #    comes first: every check below reads those same generated bytes, and there
  #    is no point asserting things about a stale copy. w-i18n-gen also validates
  #    the canonical side as it goes (language completeness, no real newline in a
  #    key=value target, printf placeholders matching across languages).
  devtools/usr/local/bin/w-i18n-gen --check > /dev/null || {
    echo "  generated i18n files are stale (see w-i18n-gen --check above)"; rc=1; }

  # 1. Dict parity — every sibling <code>.conf must carry exactly the en keys.
  #    `_`-prefixed keys are per-language metadata consumed with a `:-` fallback
  #    (_lang_name, ru-only _console_font) — exempt from parity by convention.
  local lang diff
  for lang in "$base"/*.conf; do
    [[ "$lang" == "$base/en.conf" ]] && continue
    diff="$(comm -3 <(_i18n_keys "$base/en.conf" | grep -v '^_') \
                    <(_i18n_keys "$lang" | grep -v '^_') || true)"
    [[ -z "$diff" ]] || { echo "  key mismatch en.conf vs ${lang##*/}:"; echo "$diff" | sed 's/^/    /'; rc=1; }
  done

  # 2. steps.conf: i18n keys exist; bare-identifier options/validate/condition
  #    resolve to a function defined somewhere in the installer.
  local en_keys funcs id type var title prompt opts validate cond n=0
  en_keys=" $(_i18n_keys "$base/en.conf" | tr '\n' ' ') "
  funcs=" $(grep -rhoE '^[[:space:]]*[A-Za-z_][A-Za-z0-9_]*\(\)' \
              scripts/install.sh scripts/install/lib scripts/install/modules \
            | tr -d ' ()' | sort -u | tr '\n' ' ') "
  while IFS='|' read -r id type var title prompt opts validate cond; do
    n=$((n + 1))
    id="${id//[[:space:]]/}"
    [[ -z "$id" || "$id" == \#* ]] && continue
    for k in $title $prompt; do
      [[ "$en_keys" == *" $k "* ]] || { echo "  steps.conf:$n ($id): i18n key not in en.conf: $k"; rc=1; }
    done
    # Whole field must be a bare identifier to be a function reference —
    # inline `[[ … ]]` condition expressions are runtime-only, skip them.
    local fn
    for fn in "${opts//[[:space:]]/}" "${validate//[[:space:]]/}" "${cond//[[:space:]]/}"; do
      [[ "$fn" =~ ^[A-Za-z_][A-Za-z0-9_]*$ ]] || continue
      [[ "$funcs" == *" $fn "* ]] || { echo "  steps.conf:$n ($id): function not defined: $fn"; rc=1; }
    done
  done < scripts/install/steps.conf

  # 2a. Pack descriptions have TWO English sources — the bundle's own meta.conf
  #     DESC (what `w-pack list` prints) and the catalog's `p_<name>` (what the
  #     installer checklist prints, for every language including en). They were
  #     already saying different things about `dev` and `flatpak` when this rule
  #     was written. meta.conf is the bundle's own file and therefore the source;
  #     the catalog must quote it verbatim for en, and translate it for the rest.
  local meta name desc cat_en
  for meta in scripts/packs/*/meta.conf; do
    [[ -f "$meta" ]] || continue
    name="$(basename "$(dirname "$meta")")"
    # `INSTALLER=off` bundles never reach the checklist, so they need no entry.
    [[ "$(set +u; source "$meta" 2>/dev/null; printf '%s' "${INSTALLER:-on}")" == off ]] && continue
    # Neither do maintainer bundles: no catalogue of any kind names them, so a
    # translated description would be a string with no reader.
    [[ "$(set +u; source "$meta" 2>/dev/null; printf '%s' "${AUDIENCE:-user}")" == maintainer ]] && continue
    desc="$(set +u; source "$meta" 2>/dev/null; printf '%s' "${DESC:-}")"
    cat_en="$(python3 -c 'import json,sys; d=json.load(open("i18n/installer.json")); print(d.get("p_"+sys.argv[1],{}).get("en",""))' "$name")"
    if [[ -z "$cat_en" ]]; then
      echo "  i18n/installer.json: no p_$name for checklist bundle '$name'"; rc=1
    elif [[ "$cat_en" != "$desc" ]]; then
      echo "  p_${name}[en] != $meta DESC:"; echo "    catalog:  $cat_en"; echo "    meta.conf: $desc"; rc=1
    fi
  done

  # 3. Quickshell trees: each against its own dictionary.
  local tree
  for tree in rootfs/etc/skel/.config/quickshell/w rootfs/etc/greetd/quickshell/w; do
    python3 - "$tree" <<'PY' || rc=1
import json, pathlib, re, sys
tree = pathlib.Path(sys.argv[1])
d = json.load(open(tree / "core/i18n.json"))
keys = {k for k in d if k != "_comment"}
rc = 0
for k in sorted(keys):
    missing = {"en", "ru"} - set(d[k])
    if missing:
        print(f"  i18n.json ({tree.name} tree): '{k}' missing {sorted(missing)}"); rc = 1
used = set()
for f in tree.rglob("*.qml"):
    used |= set(re.findall(r'Strings\.t\("([^"]+)"\)', f.read_text()))
for k in sorted(used - keys):
    print(f"  {tree}: Strings.t(\"{k}\") has no i18n.json entry"); rc = 1
unused = keys - used
print(f"  {tree.parent.parent.name}/{tree.name}: {len(used)} used keys, {len(unused)} unreferenced (dynamic/reserve)")
sys.exit(rc)
PY
  done
  return $rc
}
