# W Linux — generated by w-style. Do not edit; edit the theme's theme.conf.
# Sourced by ~/.zshrc (and re-sourced live by its precmd hook on theme switch).
# W-Terminal is GUI/truecolor-first: exact theme hex, not ANSI roles.

# LS_COLORS: GNU default database, then brand directory/link/exec/socket hues
# (the trailing entries win — GNU ls/eza use the last match).
eval "$(dircolors -b 2>/dev/null)"
export LS_COLORS="${LS_COLORS}di=38;2;164;133;164:ln=38;2;145;97;155:ex=38;2;165;38;191;1:pi=38;2;90;74;99:so=38;2;255;128;255:bd=38;2;90;74;99:cd=38;2;90;74;99:or=38;2;165;38;191:"

# zsh-syntax-highlighting — exact theme hex per syntactic role.
typeset -gA ZSH_HIGHLIGHT_STYLES
ZSH_HIGHLIGHT_STYLES[default]='none'
ZSH_HIGHLIGHT_STYLES[unknown-token]='fg=#e34666,bold'
ZSH_HIGHLIGHT_STYLES[reserved-word]='fg=#91619b'
ZSH_HIGHLIGHT_STYLES[alias]='fg=#a526bf,bold'
ZSH_HIGHLIGHT_STYLES[suffix-alias]='fg=#a526bf,bold'
ZSH_HIGHLIGHT_STYLES[global-alias]='fg=#a526bf,bold'
ZSH_HIGHLIGHT_STYLES[builtin]='fg=#a526bf,bold'
ZSH_HIGHLIGHT_STYLES[function]='fg=#a526bf,bold'
ZSH_HIGHLIGHT_STYLES[command]='fg=#a526bf,bold'
ZSH_HIGHLIGHT_STYLES[precommand]='fg=#a526bf,bold,underline'
ZSH_HIGHLIGHT_STYLES[hashed-command]='fg=#a526bf,bold'
ZSH_HIGHLIGHT_STYLES[arg0]='fg=#a526bf'
ZSH_HIGHLIGHT_STYLES[commandseparator]='fg=#8a7a8e'
ZSH_HIGHLIGHT_STYLES[redirection]='fg=#8a7a8e'
ZSH_HIGHLIGHT_STYLES[named-fd]='fg=#8a7a8e'
ZSH_HIGHLIGHT_STYLES[numeric-fd]='fg=#8a7a8e'
ZSH_HIGHLIGHT_STYLES[path]='fg=#a485a4'
ZSH_HIGHLIGHT_STYLES[path_prefix]='fg=#a485a4'
ZSH_HIGHLIGHT_STYLES[path_pathseparator]='fg=#8a7a8e'
ZSH_HIGHLIGHT_STYLES[path_prefix_pathseparator]='fg=#8a7a8e'
ZSH_HIGHLIGHT_STYLES[assign]='fg=#a485a4'
ZSH_HIGHLIGHT_STYLES[globbing]='fg=#ff80ff'
ZSH_HIGHLIGHT_STYLES[history-expansion]='fg=#ff80ff'
ZSH_HIGHLIGHT_STYLES[single-hyphen-option]='fg=#8a7a8e'
ZSH_HIGHLIGHT_STYLES[double-hyphen-option]='fg=#8a7a8e'
ZSH_HIGHLIGHT_STYLES[single-quoted-argument]='fg=#a197a4'
ZSH_HIGHLIGHT_STYLES[double-quoted-argument]='fg=#a197a4'
ZSH_HIGHLIGHT_STYLES[dollar-quoted-argument]='fg=#a197a4'
ZSH_HIGHLIGHT_STYLES[back-quoted-argument]='fg=#a197a4'
ZSH_HIGHLIGHT_STYLES[dollar-double-quoted-argument]='fg=#ff80ff'
ZSH_HIGHLIGHT_STYLES[comment]='fg=#8a7a8e,italic'

# zsh-autosuggestions — muted exact hex.
export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=#5a4a63'

# fzf — truecolor hex from the theme (rounded border, reverse layout).
export FZF_DEFAULT_OPTS="--height=45% --layout=reverse --border=rounded --color=hl:#a526bf,fg+:#91619b,hl+:#a526bf,info:#5a4a63,prompt:#91619b,pointer:#91619b,marker:#ff80ff,spinner:#91619b,border:#5a4a63,header:#5a4a63"

# eza — truecolor listing (extends LS_COLORS with eza fields: dates, owners,
# sizes, git status). bat follows the live ghostty palette via BAT_THEME=ansi.
export EZA_COLORS="di=38;2;164;133;164:ex=38;2;165;38;191;1:ln=38;2;145;97;155:da=38;2;90;74;99:uu=38;2;161;151;164:gu=38;2;90;74;99:sn=38;2;255;128;255:sb=38;2;90;74;99:ga=38;2;165;38;191:gm=38;2;145;97;155:gd=38;2;227;70;102:gv=38;2;255;128;255:xx=38;2;90;74;99:hd=38;2;90;74;99"

# jq — null:false:true:numbers:strings:arrays:objects:object-keys (SGR codes).
export JQ_COLORS="38;2;90;74;99:38;2;227;70;102:38;2;165;38;191:38;2;255;128;255:38;2;161;151;164:38;2;164;133;164:38;2;164;133;164:38;2;145;97;155"
