# w-style module: heroic (user-scope) — Heroic Games Launcher palette.
#
# Ships INSIDE the gaming W-Pack (source of truth); `w-pack install` drops this
# axis into the w-style modules.d drop-in root, `w-pack remove` takes it back.
# Core w-style carries no reference to Heroic → the axis exists iff the bundle
# is installed (packs.md "bundle self-containment", pack-gaming.md).
#
# Heroic is Electron: it paints from its OWN CSS custom properties, so neither
# the `gtk` nor the `qt` axis reaches it. Its sanctioned skinning channel is a
# "custom theme" — a plain .css file in a directory the app is told about:
#
#   * `customThemesPath` (a GlobalConfig setting in ~/.config/heroic/config.json)
#     names the directory; the backend lists *.css from it (`getCustomThemes`)
#     and reads the chosen one (`getThemeCSS`).
#   * `theme` (a key in ~/.config/heroic/store/config.json, electron-store) names
#     the chosen FILE, extension included.
#   * the frontend then injects the file's text as <style class="customTheme">,
#     first child of <body>, and sets document.body.className to the file name
#     WITHOUT ".css" — which is why every rule below is scoped `body.w` and the
#     rendered file must be named w.css. (src/frontend/index.tsx, setTheme)
#
# Those two config keys are seeded ONCE, per account, by the bundle's
# setup-user.sh — not here: an axis renders the active theme and owns its output
# file, it does not own the user's choice of theme (same split as the telegram
# axis vs its tdata seed). This axis only writes the file.
#
# NOT live: setTheme() runs at startup and when the user picks a theme in
# Settings; there is no watcher on the file. `w-theme set` therefore recolours
# the NEXT Heroic launch, not a running one.
#
# Two layers are overridden deliberately, and both are needed:
#   1. Heroic's own primitives (--brand-*, --neutral-*, --status-*, --accent*,
#      the gradients) from src/frontend/styles/_colors.scss. They live in :root
#      and a dozen component stylesheets reference them DIRECTLY, bypassing the
#      semantic names — leave them alone and Heroic's stock cyan leaks through
#      buttons, the alphabet filter, the sidebar version line and the download
#      manager. `body.w` (0,1,1) outranks `:root` (0,0,1), so overriding here is
#      enough; no !important anywhere.
#   2. The semantic set from src/frontend/themes.scss. A built-in theme block
#      defines ~50 of these and the rest fall back to the primitives; W sets the
#      full surface, so nothing is left to chance.
#
# Mapping principles (the roles are W's, not Heroic's; matugen's heroic template
# supplied part of the key list and nothing else — it covers ~40 of the 89
# variables and knows nothing about the primitives above):
#   * surface ramp W_BG → W_APP_BG → W_SURFACE_DIM → W_SURFACE → W_SURFACE_VARIANT
#     for window/canvas/sidebar/track/raised, exactly as every other W axis;
#   * the accent split fill/ink — W_PRIMARY FILLS (buttons, play), while
#     W_ON_SURFACE_ACCENT is the accent DRAWN as content (links, active icons,
#     focus rings, bullets);
#   * secondary/install buttons are the W selection idiom, W_PRIMARY_CONTAINER
#     + W_ON_PRIMARY_CONTAINER, not the raw accent;
#   * --text-tertiary is NOT a third text tone: _buttons.scss uses it as the
#     LABEL on a filled button (`background: var(--primary); color:
#     var(--text-tertiary)`). Heroic's own themes put near-black there because
#     their --primary is bright cyan; W's primary is a dark purple, so the label
#     is W_ON_PRIMARY. Getting this one wrong makes every button unreadable;
#   * status/anti-cheat badges ride the ANSI hue wheel, W_DANGER* for
#     destructive, translucent composites as #rrggbbaa.
# No new theme.conf tokens. Band 400 = per-app GUI config.
DESC="Heroic Games Launcher palette"

HEROIC_THEME_REL=".config/heroic/themes/w.css"

render_user() {
  local theme_dir; theme_dir="$(w_userscope_theme_dir)"
  load_conf "$theme_dir"
  echo "w-style: rendering Heroic palette..."

  local css
  css=$(cat <<EOF
/* W Linux — generated by the w-style axis 400-heroic. Do not edit; the palette
 * comes from the active theme's theme.conf. Heroic reads this file at startup
 * (and when re-picked in Settings → General), never while running: a theme
 * switch shows up at the next launch.
 *
 * The selector must match the file name minus ".css" — Heroic sets
 * document.body.className from it. Renaming the file breaks the theme.
 */

body.w {
  /* ── Heroic's own primitives (styles/_colors.scss) ─────────────────────── */
  --brand-primary: $W_PRIMARY;
  --brand-primary-hover: $W_PRIMARY_CONTAINER;
  --brand-secondary: $W_PRIMARY_SOFT;
  --brand-secondary-hover: $W_ACCENT_ALT_SOFT;
  --brand-text-01: $W_ON_SURFACE_BRIGHT;
  --brand-text-02: $W_ON_SURFACE;
  --brand-text-03: $W_ON_SURFACE_ACCENT;
  --brand-text-04: $W_ON_SURFACE_VARIANT;
  --brand-text-05: $W_ON_SURFACE_VIVID;

  --neutral-01: $W_BG;
  --neutral-02: $W_APP_BG;
  --neutral-03: $W_SURFACE_DIM;
  --neutral-04: $W_SURFACE;
  --neutral-05: $W_ON_SURFACE_VARIANT;
  --neutral-06: $W_ON_SURFACE;
  --neutral-07: $W_ON_SURFACE_BRIGHT;
  --neutral-08: $W_ON_SURFACE_BRIGHT;
  --base-06: $W_ON_SURFACE_VARIANT;

  --status-default: $W_ON_SURFACE;
  --status-default-hover: $W_ON_SURFACE_BRIGHT;
  --status-success: $W_TERM_ANSI_GREEN;
  --status-success-hover: $W_TERM_ANSI_BRIGHT_GREEN;
  --status-warning: $W_TERM_ANSI_YELLOW;
  --status-warning-hover: $W_TERM_ANSI_BRIGHT_YELLOW;
  --status-danger: $W_DANGER;
  --status-danger-hover: $W_TERM_ANSI_BRIGHT_RED;
  --status-info: $W_TERM_ANSI_CYAN;
  --status-info-hover: $W_TERM_ANSI_BRIGHT_CYAN;
  --status-denied: $W_ON_SURFACE_FAINT;

  --accent: $W_ON_SURFACE_ACCENT;
  --accent-02: ${W_PRIMARY}5b;
  --accent-overlay: $W_PRIMARY_SOFT;
  --primary-active: $W_PRIMARY_SOFT;
  --secondary-hover: $W_ACCENT_ALT_SOFT;
  --secondary-active: $W_ACCENT_ALT;
  --eighty-percent-black: ${W_BG}cc;
  --sixty-percent-black: ${W_BG}99;

  /* ── Surfaces ──────────────────────────────────────────────────────────── */
  --background: $W_SURFACE;
  --background-darker: $W_BG;
  --background-darker-80: ${W_BG}cc;
  --background-lighter: $W_SURFACE_VARIANT;
  --background-light: $W_SURFACE_VARIANT;
  --background-secondary: $W_SURFACE_DIM;
  --background-hover: $W_SURFACE_VARIANT;
  --body-background: $W_APP_BG;
  --current-background: $W_APP_BG;
  --bg-primary: $W_SURFACE;
  --gradient-body-background: linear-gradient(
    90deg,
    $W_BG -32px,
    $W_APP_BG 64px,
    $W_APP_BG 100%
  );
  --background-gradient: linear-gradient(90deg, $W_SURFACE_DIM, $W_APP_BG);
  --input-background: $W_SURFACE_VARIANT;
  --search-bar-background: $W_SURFACE_DIM;
  --search-bar-border: $W_SURFACE_VARIANT;
  --icons-background: $W_SURFACE_DIM;
  --controller-hints-background: ${W_BG}cc;
  --divider: $W_SURFACE_VARIANT;
  --border-color: $W_SURFACE_VARIANT;

  /* ── Modals and popovers ───────────────────────────────────────────────── */
  --modal-background: $W_SURFACE;
  --modal-backdrop: ${W_BG}cc;
  --modal-border: $W_SURFACE_VARIANT;

  /* ── Sidebar ───────────────────────────────────────────────────────────── */
  --navbar-background: $W_SURFACE_DIM;
  --navbar-active-background: $W_SURFACE_VARIANT;
  --navbar-active: $W_ON_SURFACE_BRIGHT;
  --navbar-inactive: $W_ON_SURFACE_VARIANT;
  --navbar-accent: $W_ON_SURFACE_ACCENT;

  /* ── Text ──────────────────────────────────────────────────────────────── */
  --text-default: $W_ON_SURFACE;
  --text-secondary: $W_ON_SURFACE_VARIANT;
  --text-tertiary: $W_ON_PRIMARY;
  --text-quartenary: $W_ON_SURFACE_FAINT;
  --text-title: $W_ON_SURFACE_BRIGHT;
  --text-gametitle: $W_ON_SURFACE_BRIGHT;
  --text-hover: $W_ON_SURFACE_BRIGHT;
  --text-primary: $W_ON_SURFACE;
  --text-muted: $W_ON_SURFACE_FAINT;
  --text-log: $W_ON_SURFACE_VARIANT;
  --text-danger: $W_DANGER;
  --text-warning: $W_TERM_ANSI_YELLOW;
  --text-pause-cancel: $W_TERM_ANSI_YELLOW;
  --link-highlight: $W_ON_SURFACE_ACCENT;

  /* ── Action icons ──────────────────────────────────────────────────────── */
  --action-icon: $W_ON_SURFACE_VARIANT;
  --action-icon-hover: $W_ON_SURFACE_ACCENT;
  --action-icon-active: $W_ON_SURFACE_BRIGHT;
  --icon-disabled: $W_ON_SURFACE_FAINT;
  --icon-disabled-overlay: $W_SURFACE_VARIANT;

  /* ── Buttons ───────────────────────────────────────────────────────────── */
  --primary: $W_PRIMARY;
  --primary-hover: $W_PRIMARY_CONTAINER;
  --secondary: $W_PRIMARY_CONTAINER;
  --primary-button: $W_PRIMARY;
  --play-button: $W_PRIMARY;
  --secondary-button: $W_PRIMARY_CONTAINER;
  --secondary-button-overlay: $W_PRIMARY;
  --install-button: $W_PRIMARY_CONTAINER;
  --install-button-hover: $W_PRIMARY;
  --download-button: $W_ON_SURFACE_ACCENT;
  --download-button-overlay: $W_PRIMARY;
  --tertiary-button: $W_SURFACE;
  --tertiary-button-overlay: $W_SURFACE_VARIANT;
  --success-button: $W_TERM_ANSI_GREEN;
  --cancel-button: $W_DANGER;
  --cancel-button-overlay: $W_TERM_ANSI_BRIGHT_RED;
  --cancel-button-hover: $W_TERM_ANSI_BRIGHT_RED;
  --stop-button: $W_DANGER;
  --disabled-button: $W_SURFACE_DIM;
  --disabled-button-overlay: $W_ON_SURFACE_FAINT;
  --button-stroke: $W_ON_SURFACE_ACCENT;

  /* ── Status ────────────────────────────────────────────────────────────── */
  --success: $W_TERM_ANSI_GREEN;
  --success-hover: $W_TERM_ANSI_BRIGHT_GREEN;
  --danger: $W_DANGER;
  --danger-hover: $W_TERM_ANSI_BRIGHT_RED;
  --error: $W_ERROR;
  --warning: $W_TERM_ANSI_YELLOW;
  --warning-hover: $W_TERM_ANSI_BRIGHT_YELLOW;

  /* ── Anti-cheat badges (the ANSI hue wheel) ────────────────────────────── */
  --anticheat-denied: $W_DANGER;
  --anticheat-broken: $W_TERM_ANSI_RED;
  --anticheat-running: $W_TERM_ANSI_BLUE;
  --anticheat-supported: $W_TERM_ANSI_GREEN;
  --anticheat-planned: $W_TERM_ANSI_YELLOW;
  --anticheat-unknown: $W_ON_SURFACE_FAINT;

  /* ── On-screen keyboard (gamepad navigation) ───────────────────────────── */
  --osk-background: $W_SURFACE;
  --osk-button-background: $W_SURFACE_VARIANT;
  --osk-button-border: $W_SURFACE_DIM;

  /* ── Library game cards and the alphabet filter ────────────────────────── */
  --gamecard-title-color: ${W_APP_BG}cc;
  --gradient-gamecard: linear-gradient(
    180deg,
    ${W_BG}6b 1.8%,
    ${W_APP_BG}cc 45%
  );
  --alphabet-filter-accent-color: $W_ON_SURFACE_ACCENT;
  --alphabet-filter-accent-hover: $W_PRIMARY_SOFT;

  /* ── Onboarding tour popups ────────────────────────────────────────────── */
  --tour-popup-background: $W_SURFACE;
  --tour-popup-title: $W_ON_SURFACE_BRIGHT;
  --tour-popup-skip-color: $W_ON_SURFACE_VARIANT;
  --tour-popup-skip-color-hover: $W_ON_SURFACE_BRIGHT;
  --tour-button-color: $W_PRIMARY;
  --tour-bullet-active: $W_ON_SURFACE_ACCENT;
  --tour-bullet-inactive: $W_ON_SURFACE_FAINT;

  /* ── Window Controls Overlay (frameless window) ────────────────────────── */
  /* setTheme() reads these off the body and hands them to Electron's
   * setTitleBarOverlay, so they must be plain colours, not var() chains. */
  --titlebar-color: $W_APP_BG;
  --titlebar-symbol-color: $W_ON_SURFACE;
}
EOF
)

  # Sentinel first: under `set -u` a typo'd token name kills the command
  # substitution INSIDE its subshell, the assignment survives empty, and an
  # empty stylesheet would ship as a valid-looking theme — Heroic would apply
  # `body.w` with no declarations and fall back to its stock cyan, which looks
  # like "the axis did nothing" rather than an error.
  if [[ -z "$css" || ! "$css" == *"--body-background:"* ]]; then
    echo "w-style: heroic — rendered stylesheet is empty/malformed (token typo?), refusing to write." >&2
    return 1
  fi

  printf '%s\n' "$css" | write_user_file "$HEROIC_THEME_REL"

  if [[ $EUID -eq 0 ]]; then
    echo "w-style: heroic done (skel template; accounts pick it up at their next login render)."
  else
    echo "w-style: heroic done (next Heroic launch shows the new colours)."
  fi
}
