# w-style module: ghostty (user-scope) — terminal palette + bg translucency.
# Terminal translucency comes from the effects axis (own knob W_FX_TERM_OPACITY) —
# bg only, text stays opaque; the compositor blurs behind. Rendered into the theme
# file, then live-applied to running windows via SIGUSR2 (this module owns that
# reload — formerly done by w-theme). Band 500 = terminal/CLI.
DESC="Ghostty terminal palette + bg opacity"

GHOSTTY_THEME_REL=".config/ghostty/themes/w"

render_user() {
  local theme_dir; theme_dir="$(w_userscope_theme_dir)"
  load_conf "$theme_dir"
  load_effects "$(resolve_theme_file "$theme_dir" effects.conf)"
  echo "w-style: rendering Ghostty theme..."

  write_user_file "$GHOSTTY_THEME_REL" <<EOF
# W Linux — generated by w-style. Do not edit; edit the theme's theme.conf / effects.conf.
background = $W_TERM_BG
background-opacity = $W_FX_TERM_OPACITY
foreground = $W_TERM_FG
cursor-color = $W_TERM_CURSOR
cursor-text = $W_TERM_CURSOR_TEXT
selection-background = $W_TERM_SELECTION_BG
selection-foreground = $W_TERM_SELECTION_FG

palette = 0=$W_TERM_ANSI_BLACK
palette = 1=$W_TERM_ANSI_RED
palette = 2=$W_TERM_ANSI_GREEN
palette = 3=$W_TERM_ANSI_YELLOW
palette = 4=$W_TERM_ANSI_BLUE
palette = 5=$W_TERM_ANSI_MAGENTA
palette = 6=$W_TERM_ANSI_CYAN
palette = 7=$W_TERM_ANSI_WHITE
palette = 8=$W_TERM_ANSI_BRIGHT_BLACK
palette = 9=$W_TERM_ANSI_BRIGHT_RED
palette = 10=$W_TERM_ANSI_BRIGHT_GREEN
palette = 11=$W_TERM_ANSI_BRIGHT_YELLOW
palette = 12=$W_TERM_ANSI_BRIGHT_BLUE
palette = 13=$W_TERM_ANSI_BRIGHT_MAGENTA
palette = 14=$W_TERM_ANSI_BRIGHT_CYAN
palette = 15=$W_TERM_ANSI_BRIGHT_WHITE
EOF

  # Live channel: make this user's running Ghostty windows re-read the config
  # (theme + font). Ghostty (>=1.2) reloads on SIGUSR2; any other signal crashes it,
  # so target exactly the ghostty binary (name < 15 chars, -x is safe). Harmless if
  # none running. Skipped at root/install (skel render has no session to recolor).
  if [[ $EUID -ne 0 ]]; then pkill -USR2 -x ghostty 2>/dev/null || true; fi

  echo "w-style: Ghostty done."
}
