# w-style module: wiremix (user-scope) — PipeWire TUI-mixer theme (Tier-2 roles).
# wiremix reads a single config and MERGES it over its built-ins, so we write a
# minimal file: it selects theme "w" and defines [themes.w] (inheriting built-in
# "default" for anything unset) — keybindings/options stay wiremix's defaults.
# Styles use ratatui's { fg, bg, add_modifier } with "#RRGGBB". Opened from the
# Volume Control popup ("Open Mixer"). NOT live (next launch). Band 500 = CLI/TUI.
DESC="wiremix PipeWire-mixer theme (TUI)"

WIREMIX_CONF_REL=".config/wiremix/wiremix.toml"

render_user() {
  load_conf "$(w_userscope_theme_dir)"
  echo "w-style: rendering wiremix theme..."

  write_user_file "$WIREMIX_CONF_REL" <<EOF
# W Linux — generated by w-style. Do not edit; edit the theme's theme.conf.
theme = "w"

[themes.w]
inherit = "default"
# Default device/endpoint markers + selection accent
default_device = { fg = "$W_PRIMARY" }
default_stream = { fg = "$W_PRIMARY" }
selector = { fg = "$W_PRIMARY", add_modifier = "BOLD" }
# Tab menu
tab = { fg = "$W_ON_SURFACE_VARIANT" }
tab_selected = { fg = "$W_PRIMARY", add_modifier = "BOLD" }
tab_marker = { fg = "$W_PRIMARY" }
list_more = { fg = "$W_ON_SURFACE_VARIANT" }
# Node / routing labels
node_title = { fg = "$W_ON_SURFACE" }
node_target = { fg = "$W_PRIMARY" }
# Volume slider + percentage
volume = { fg = "$W_ON_SURFACE" }
volume_empty = { fg = "$W_SURFACE_VARIANT" }
volume_filled = { fg = "$W_PRIMARY" }
# Peak meters (active → accent, overload → error)
meter_inactive = { fg = "$W_SURFACE_VARIANT" }
meter_active = { fg = "$W_PRIMARY" }
meter_overload = { fg = "$W_ERROR" }
meter_center_inactive = { fg = "$W_SURFACE_VARIANT" }
meter_center_active = { fg = "$W_PRIMARY" }
# Configuration tab (device/profile)
config_device = { fg = "$W_ON_SURFACE" }
config_profile = { fg = "$W_ON_SURFACE_VARIANT" }
# Routing dropdown
dropdown_icon = { fg = "$W_PRIMARY" }
dropdown_border = { fg = "$W_SURFACE_VARIANT" }
dropdown_item = { fg = "$W_ON_SURFACE" }
dropdown_selected = { fg = "$W_ON_PRIMARY_CONTAINER", bg = "$W_PRIMARY_CONTAINER", add_modifier = "BOLD" }
dropdown_more = { fg = "$W_ON_SURFACE_VARIANT" }
# Help overlay
help_border = { fg = "$W_SURFACE_VARIANT" }
help_item = { fg = "$W_ON_SURFACE" }
help_more = { fg = "$W_ON_SURFACE_VARIANT" }
EOF

  echo "w-style: wiremix done (applies to the next wiremix invocation)."
}
