# w-style module: quickshell (user-scope, JSON) — shell palette + brand logo path.
# Colors.qml/Logo.qml read these via FileView{watchChanges}, so a running shell
# recolors live with no signal/reload. Written IN-PLACE (write_user_file) so the
# watched inode survives a theme switch. Band 100 = shell surfaces.
#
# `accentInk` is the accent as CONTENT (a button outline, a tab label, an icon)
# as opposed to `accent`, which fills a shape. They cannot be one token: a fill
# is built to sit close to its surface, which is exactly what makes it unreadable
# as a line — measured 1.10:1 on a light theme's card. Themes generated before
# the split have no such token, hence the fallback to the card border accent.
#
# `iconTheme` is here even though this axis does not render icons: it is how the
# shell learns that the ICON theme changed under it. Qt resolves themed icons
# against a name it picks up from qt6ct, and Quickshell hands QML the provider URL
# image://icon/<name> — which is identical before and after a theme switch, so the
# pixmap cache keeps serving the old icons. Seeing the name change is what lets the
# shell re-request them (core/IconTheme.qml).
DESC="Quickshell shell palette + logo path (JSON, live)"

QS_COLORS_REL=".config/quickshell/w/core/colors.json"
QS_LOGO_REL=".config/quickshell/w/core/logo.json"   # brand logo path (theme `w-logo` bar icon)

render_user() {
  load_conf "$(w_userscope_theme_dir)"
  echo "w-style: rendering Quickshell colors..."

  write_user_file "$QS_COLORS_REL" <<EOF
{
  "_comment": "W Linux — generated by w-style. Do not edit; edit the theme's theme.conf.",
  "backdrop": "$W_QS_BACKDROP",
  "surface":  "$W_QS_SURFACE",
  "inputBg":  "$W_QS_INPUT_BG",
  "text":     "$W_QS_TEXT",
  "muted":    "$W_QS_MUTED",
  "accent":   "$W_QS_ACCENT",
  "accentFg": "$W_QS_ACCENT_FG",
  "accentInk": "${W_QS_ACCENT_INK:-$W_QS_BORDER}",
  "border":   "$W_QS_BORDER",
  "iconTint": "$W_QS_ICON_TINT",
  "iconTheme": "$W_ICON_THEME",
  "dangerBg":     "$W_QS_DANGER_BG",
  "dangerFg":     "$W_QS_DANGER_FG",
  "dangerBorder": "$W_QS_DANGER_BORDER"
}
EOF

  # Brand vector logo for the shell's `w-logo` bar icon: the active theme's
  # logo/W-logo.svg, falling back to the baseline `w` theme when a theme omits it
  # (same resolve as the GRUB/Plymouth logo). The absolute path is emitted as JSON;
  # the Logo.qml singleton reads it via FileView and a theme switch changes the
  # path (per-theme dir) so the Image reloads live.
  local logo_svg; logo_svg="$(resolve_theme_file "$(w_userscope_theme_dir)" "$THEME_LOGO_SVG_REL")"
  write_user_file "$QS_LOGO_REL" <<EOF
{
  "_comment": "W Linux — generated by w-style. Do not edit; place logo/W-logo.svg in the theme.",
  "svg": "$logo_svg"
}
EOF

  echo "w-style: Quickshell done (FileView live-reloads via watchChanges)."
}
