-- W Linux — generated by w-style (apply motion). Do not edit; edit the active
-- theme's motion.conf (default /etc/w/themes/w/motion.conf).
-- Self-applying Lua module require()d by hyprland.lua: declares the shared `snap`
-- curve and the animation leaves. Speeds are deciseconds (ms/100); the `snap`
-- bezier is shared with Quickshell (motion.json below).
hl.config({ animations = { enabled = true } })
hl.curve("snap", { type = "bezier", points = { {0.25, 0.1}, {0.25, 1.0} } })
hl.animation({ leaf = "windows",    enabled = true,  speed = 3, bezier = "snap" })
hl.animation({ leaf = "windowsIn",  enabled = false })
hl.animation({ leaf = "fade",       enabled = true,  speed = 3, bezier = "snap" })
hl.animation({ leaf = "workspaces", enabled = true,  speed = 3, bezier = "snap" })
hl.animation({ leaf = "layers",     enabled = true,  speed = 4, bezier = "snap", style = "fade" })
