-- W Linux — generated by w-style. Do not edit; edit the theme's theme.conf instead.
-- require()d by hyprland.lua; values go into general.col.* + misc.background_color
-- and the group{}/groupbar{} block (tab pills).
return {
  border_active = "rgba(91619bff)",
  border_inactive = "rgba(200030ff)",
  bg = "rgba(000000ff)",
  group_border_active = "rgba(91619bff)",
  group_border_inactive = "rgba(200030ff)",
  tab_active_bg = "rgba(643670ff)",
  tab_inactive_bg = "rgba(2e0045ff)",
  tab_active_fg = "rgba(ffffffff)",
  tab_inactive_fg = "rgba(a197a4ff)",
}
