-- W Linux — generated by w-style (apply effects). Do not edit; edit the active
-- theme's effects.conf (default /etc/w/themes/w/effects.conf).
-- Lua data module require()d by hyprland.lua; values go into decoration{} (active/
-- inactive/fullscreen opacity + blur) and the blur layer rules (ignore_alpha).
return {
  opacity_active = 1.0,
  opacity_inactive = 1.0,
  opacity_fullscreen = 1.0,
  blur_enabled = true,
  blur_size = 3,
  blur_passes = 3,
  blur_ignore_alpha = 0.3,
  app_bg = 0.85,
}
