-- W Linux — generated by w-style (apply geometry). Do not edit; edit the active
-- theme's geometry.conf (default /etc/w/themes/w/geometry.conf).
-- Lua data module require()d by hyprland.lua; values go into general{} + decoration{}.
return {
  gaps_in = 4,
  gaps_out = 8,
  border = 2,
  rounding = 14,
  tab_height = 20,
  tab_rounding = 10,
  tab_gap = 4,
  tab_gap_in = 4,
}
