# w-style module: firefox (user-scope) — concept ③ chrome translucency.
# Firefox already follows the theme COLORS live (it is a GTK app; the `gtk` axis
# recolors a running Firefox via gsettings, no restart). This axis adds ONLY the
# translucency: it wraps the live system color -moz-dialog (which tracks the GTK
# theme) in color-mix() so the chrome fill keeps following the theme while gaining
# alpha from W_FX_APP_BG_OPACITY — never hard-codes a color here (that would freeze
# the live recolor). On Wayland Firefox natively supports CSD translucency: under
# @media (-moz-gtk-csd-transparency-available) it makes :root transparent itself, so
# this works with NO about:config prefs and NO Hyprland opacity rule. Rendered into
# the pinned profile's chrome/userChrome.css (deterministic path: profiles.ini +
# MOZ_LEGACY_PROFILES pin w.default). NOT live — needs a Firefox restart to apply an
# opacity change; the color stays live. The web content area is opaque by design
# (each page paints its own background), so translucency shows in the chrome only.
DESC="Firefox chrome translucency (concept ③)"

FIREFOX_USERCHROME_REL=".mozilla/firefox/w.default/chrome/userChrome.css"  # ③ chrome translucency (alpha only; color stays live from GTK)

render_user() {
  load_effects "$(resolve_theme_file "$(w_userscope_theme_dir)" effects.conf)"
  local o pct
  o="${W_FX_APP_BG_OPACITY:-1.0}"
  pct=$(awk -v o="$o" 'BEGIN{p=int(o*100+0.5); if(p<0)p=0; if(p>100)p=100; print p}')
  echo "w-style: rendering Firefox chrome translucency (${pct}%)..."

  write_user_file "$FIREFOX_USERCHROME_REL" <<EOF
/* W Linux — generated by w-style (apply firefox). Do not edit; edit the active
 * theme's effects.conf (W_FX_APP_BG_OPACITY). Concept ③: COLOR stays live from the
 * GTK/system theme (-moz-dialog follows the gtk axis), only the translucency % is
 * baked here. Restart Firefox to apply an opacity change; color changes are live.
 * Web content stays opaque by design. Single @namespace (html) is intentional —
 * the default (XUL) namespace is left unset so the bare-id rules below still match.
 * FF152 paints the chrome backdrop on <html:body> + #navigator-toolbox, and makes
 * :root transparent itself via @media (-moz-gtk-csd-transparency-available), so no
 * prefs and no Hyprland opacity rule are needed. */
@namespace html url("http://www.w3.org/1999/xhtml");

:root {
  --w-fx-app-bg: ${pct}%;   /* W_FX_APP_BG_OPACITY */
}

html|body {
  background-color: color-mix(in srgb, -moz-dialog var(--w-fx-app-bg), transparent) !important;
}

#navigator-toolbox {
  border-bottom: none !important;
}

#nav-bar {
  background-color: transparent !important;
  border-top: none !important;
}

#browser {
  background-color: transparent !important;
}

#tabbrowser-tabs::before {
  content: none !important;
}
EOF

  echo "w-style: Firefox done (restart Firefox to apply opacity; color is live)."
}
