# w-style module: mpv (user-scope) — OSD palette + brand audio equalizer.
# Renders the theme fragment ~/.config/mpv/w-theme.conf, which the skel mpv.conf
# includes via `~~/w-theme.conf`. Two concerns:
#   • OSD/background colours from Tier-2 role tokens.
#   • An audio-only VISUALIZER: a conditional auto-profile that, when the file has
#     audio but no real moving video (plain audio or embedded cover-art), draws a
#     classic 20-band equalizer — jumping frequency bars in the brand accent on
#     the theme background. Real videos are untouched.
#
# Equalizer graph (ffmpeg via lavfi-complex):
#   showfreqs draws one bar per horizontal pixel, so rendering at width 20 then
#   nearest-neighbour upscaling gives exactly 20 fat bars; fscale=log spreads
#   ~20 Hz–20 kHz; averaging is off (default) → snappy jumping bars. showfreqs'
#   canvas is always black, so we key the black transparent (colorkey) and overlay
#   the bars on a theme-coloured `color` source; drawgrid in the bg colour carves
#   the gaps between bars (1280/20 = 64 px pitch).
#
# Colours are baked in (mpv.conf has no variables), so this is NOT live — it
# applies to newly launched mpv instances. Band 500 = app/config tier.
DESC="mpv OSD palette + brand audio equalizer"

MPV_THEME_REL=".config/mpv/w-theme.conf"

render_user() {
  local theme_dir; theme_dir="$(w_userscope_theme_dir)"
  load_conf "$theme_dir"
  load_font "$(resolve_theme_file "$theme_dir" font.conf)"
  echo "w-style: rendering mpv theme..."

  # ffmpeg colours as 0xRRGGBB (avoids '#', which mpv.conf could read as comment).
  local accent="0x${W_PRIMARY#\#}" bg="0x${W_APP_BG#\#}"

  write_user_file "$MPV_THEME_REL" <<EOF
# W Linux — generated by w-style. Do not edit; edit the theme's theme.conf.

# ── OSD / letterbox palette ─────────────────────────────────────────────────
osd-font='$W_FONT_UI'
background-color='$W_APP_BG'
osd-color='$W_ON_SURFACE'
osd-back-color='$W_SURFACE'
osd-border-color='$W_BG'

# ── Audio equalizer visualizer ──────────────────────────────────────────────
# Enable only when there is audio and no real moving video (plain audio file or
# embedded cover-art). 20 brand-accent bars on the theme background; reverts on
# the next file (profile-restore=copy-equal).
#
# Tuned light + smooth: 640x360@30 canvas (cheap; mpv upscales to the window).
# acompressor tames level slams. Smoothness knobs on showfreqs, all free:
#   averaging=3  temporal moving-average over 3 frames → smooth bar tops, no
#                frame-to-frame jitter, still responsive (~100 ms at 30 fps).
#   win_func=blackman  low spectral leakage vs hanning → cleaner, less noisy bars.
#   rate=30      match the canvas fps (showfreqs defaults to 25) so overlay
#                doesn't dup/drop frames → no micro-stutter.
[visualizer]
profile-desc=W audio equalizer
profile-cond=get("current-tracks/audio") ~= nil and (get("current-tracks/video") == nil or get("current-tracks/video/image", false))
profile-restore=copy-equal
lavfi-complex=[aid1]asplit[ao][a];color=c=$bg:s=640x360:r=25[canvas];[a]aformat=channel_layouts=mono,acompressor=threshold=0.125:ratio=5:attack=3:release=250:detection=peak,showfreqs=s=20x360:rate=25:mode=bar:ascale=cbrt:fscale=log:win_size=1024:win_func=blackman:averaging=3:colors=$accent,scale=640:360:flags=neighbor,setsar=1,colorkey=0x000000:0.10:0.0[bars];[canvas][bars]overlay=shortest=1,drawgrid=w=32:h=360:t=3:c=$bg,format=yuv420p[vo]
EOF

  echo "w-style: mpv done (applies to newly launched mpv instances)."
}
