# w-style module: telegram (user-scope) — Telegram Desktop palette.
#
# Ships INSIDE the telegram W-Pack (source of truth); `w-pack install telegram`
# drops this axis into the w-style modules.d drop-in root, `w-pack remove` takes
# it back. Core w-style carries no reference to Telegram → the axis exists iff
# the bundle is installed (packs.md "bundle self-containment", pack-telegram.md).
#
# Telegram Desktop (tdesktop) is Qt but paints every pixel from its OWN palette
# (~590 named colours, `colors.palette` in lib_ui) — the `qt` axis does not reach
# it. Its theme format: a plain-text palette (`key: #rrggbb[aa];` or
# `key: otherKey;`) — or a ZIP holding that text as `colors.tdesktop-theme` plus
# a chat wallpaper (`background.{jpg,png}` stretched, `tiled.{jpg,png}` tiled;
# window_theme.cpp loadBackground). Keys left unset are derived from the ones
# set (the default palette is mostly aliases), unknown keys are ignored.
#
# This axis writes the ZIP form: the palette plus a one-colour `tiled.png`, so
# the chat wallpaper is a flat W surface instead of tdesktop's stock pattern
# (its bundled wallpapers are all light or busy; there is no "plain colour"
# choice for a local theme, and a theme's own background is the sanctioned
# channel). A theme that carries a background applies it on every Apply —
# including the live reload — so the wallpaper is the theme's, not the user's:
# a wallpaper picked in Chat settings lasts until the next theme render. That
# is the intended ownership (W owns Telegram's look while the pack is on).
# Target: `w.tdesktop-theme` in the app's own data dir next to `tdata/` (skel
# as root → every new account has it).
#
# Which theme tdesktop USES lives in its encrypted `tdata`, with no external
# "apply" channel. Two ways this file gets there: an account whose Telegram
# never ran gets a seeded tdata from the bundle's setup-user.sh (tdata-seed.py
# — settingss + a theme record pointing here, so the first launch is already
# W); an account with a running history applies it ONCE by hand, after signing
# in (Chat settings exist only with an account): Settings → Chat settings →
# Chat background → "Choose from file" → this file → Keep changes. Either way,
# from then on everything is automatic (verified in the tdesktop source, `dev`
# branch, 2026-09-12):
#   * LIVE — tdesktop puts a QFileSystemWatcher on the applied file and calls
#     Apply()+KeepApplied() on every change, silently: `w-theme set` recolours a
#     running Telegram. Needs the in-place write of write_user_file (same inode).
#   * At START — readThemeUsingKey() re-reads the file and, if its content
#     differs from the cached copy, drops the cache: a theme switched while the
#     app was closed shows up at the next launch.
#
# Mapping principles (matugen's telegram template served as the key list; the
# roles are W's, not Material's): the surface ramp W_APP_BG → SURFACE_DIM →
# SURFACE → SURFACE_VARIANT for window/hover/ripple/raised; text tones
# W_ON_SURFACE* (names and bold = BRIGHT); the accent split fill/ink as
# everywhere in W — W_PRIMARY fills buttons and badges, W_ON_SURFACE_ACCENT is
# the accent drawn as text (links, service lines, active labels); outgoing
# bubbles are the W selection idiom, W_PRIMARY_CONTAINER + ON_PRIMARY_CONTAINER
# (the active-tab / launcher-row / terminal-selection pair), not the raw accent;
# the eight peer-name colours and the file-thumbnail hues are the ANSI wheel;
# W_DANGER* for errors and destructive; translucent composites as #rrggbbaa.
# No new theme.conf tokens. Band 400 = per-app GUI config.
DESC="Telegram Desktop palette"

TELEGRAM_THEME_REL=".local/share/TelegramDesktop/w.tdesktop-theme"

# Binary twin of write_user_file: same scope rule (skel as root, $HOME as user),
# same IN-PLACE semantics (truncate + write keeps the inode tdesktop's
# QFileSystemWatcher is armed on) — write_user_file itself goes through a bash
# string and would drop the NUL bytes of a ZIP. $1 = relative target, $2 = file.
_tg_write_binary() {
  local rel="$1" src="$2" target
  if [[ $EUID -eq 0 ]]; then target="/etc/skel/$rel"; else target="$HOME/$rel"; fi
  mkdir -p "$(dirname "$target")"
  cat "$src" >"$target" && chmod 644 "$target"
}

render_user() {
  local theme_dir; theme_dir="$(w_userscope_theme_dir)"
  load_conf "$theme_dir"
  echo "w-style: rendering telegram palette..."

  local palette
  palette=$(cat <<EOF
// W Linux — generated by the w-style axis 400-telegram (colors.tdesktop-theme
// inside w.tdesktop-theme, next to the flat tiled.png chat wallpaper). Do not
// edit; the palette comes from the active theme's theme.conf. Telegram uses it
// from its first launch (seeded tdata) or after one pick in Settings → Chat
// settings → Chat background → Choose from file; either way it then watches
// the file, and every theme switch recolours it live.

// --- Window & basic ---
windowBg: $W_APP_BG;
windowFg: $W_ON_SURFACE;
windowBgOver: $W_SURFACE_DIM;
windowBgRipple: $W_SURFACE;
windowFgOver: $W_ON_SURFACE_BRIGHT;
windowSubTextFg: $W_ON_SURFACE_VARIANT;
windowSubTextFgOver: $W_ON_SURFACE;
windowBoldFg: $W_ON_SURFACE_BRIGHT;
windowBoldFgOver: $W_ON_SURFACE_BRIGHT;
windowBgActive: $W_PRIMARY;
windowFgActive: $W_ON_PRIMARY;
windowActiveTextFg: $W_ON_SURFACE_ACCENT;
windowShadowFg: ${W_SHADOW}5c;
windowShadowFgFallback: $W_APP_BG;
shadowFg: ${W_ON_SURFACE}33;
slideFadeOutBg: ${W_SHADOW}3c;
slideFadeOutShadowFg: ${W_SHADOW}5c;
imageBg: $W_APP_BG;
imageBgTransparent: $W_ON_SURFACE_BRIGHT;

// --- Buttons ---
activeButtonBg: $W_PRIMARY;
activeButtonBgOver: ${W_PRIMARY}e6;
activeButtonBgRipple: ${W_PRIMARY}cc;
activeButtonFg: $W_ON_PRIMARY;
activeButtonFgOver: $W_ON_PRIMARY;
activeButtonSecondaryFg: ${W_ON_PRIMARY}cc;
activeButtonSecondaryFgOver: $W_ON_PRIMARY;
activeLineFg: $W_PRIMARY;
activeLineFgError: $W_DANGER;
lightButtonBg: $W_APP_BG;
lightButtonBgOver: $W_SURFACE_DIM;
lightButtonBgRipple: $W_SURFACE;
lightButtonFg: $W_ON_SURFACE_ACCENT;
lightButtonFgOver: $W_ON_SURFACE_VIVID;
attentionButtonFg: $W_DANGER;
attentionButtonFgOver: $W_ON_ERROR;
attentionButtonBgOver: $W_DANGER;
attentionButtonBgRipple: ${W_DANGER}cc;

// --- Menus ---
menuBg: $W_SURFACE;
menuBgOver: $W_SURFACE_VARIANT;
menuBgRipple: ${W_PRIMARY}33;
menuIconFg: $W_ON_SURFACE_VARIANT;
menuIconFgOver: $W_ON_SURFACE_ACCENT;
menuSubmenuArrowFg: $W_ON_SURFACE_VARIANT;
menuFgDisabled: $W_ON_SURFACE_FAINT;
menuSeparatorFg: $W_ON_SURFACE_FAINT;

// --- Scrollbars & inputs ---
scrollBarBg: ${W_ON_SURFACE}33;
scrollBarBgOver: ${W_ON_SURFACE}66;
scrollBg: ${W_SHADOW}1a;
scrollBgOver: ${W_SHADOW}2c;
historyScrollBarBg: ${W_ON_SURFACE}33;
historyScrollBarBgOver: ${W_ON_SURFACE}66;
historyScrollBg: ${W_SHADOW}1a;
historyScrollBgOver: ${W_SHADOW}2c;
smallCloseIconFg: $W_ON_SURFACE_VARIANT;
smallCloseIconFgOver: $W_ON_SURFACE;
radialFg: $W_ON_PRIMARY_CONTAINER;
radialBg: ${W_SHADOW}56;
placeholderFg: $W_ON_SURFACE_VARIANT;
placeholderFgActive: $W_ON_SURFACE_FAINT;
inputBorderFg: $W_ON_SURFACE_FAINT;
filterInputBorderFg: $W_PRIMARY;
checkboxFg: $W_ON_SURFACE_VARIANT;
sliderBgInactive: $W_SURFACE_VARIANT;
sliderBgActive: $W_PRIMARY;
tooltipBg: $W_SURFACE_VARIANT;
tooltipFg: $W_ON_SURFACE;
tooltipBorderFg: $W_SURFACE_VARIANT;
spellUnderline: ${W_DANGER}88;
searchedTextMatchBg: $W_TERM_ANSI_YELLOW;
searchedTextMatchFg: $W_APP_BG;
searchedTextCurrentMatchBg: $W_TERM_ANSI_BRIGHT_YELLOW;
searchedTextCurrentMatchFg: $W_APP_BG;

// --- Title bar & tray ---
titleBg: $W_APP_BG;
titleShadow: ${W_SHADOW}03;
titleButtonFg: $W_ON_SURFACE_VARIANT;
titleButtonBgOver: $W_SURFACE_DIM;
titleButtonFgOver: $W_ON_SURFACE;
titleButtonCloseBgOver: $W_DANGER;
titleButtonCloseFgOver: $W_ON_ERROR;
titleFgActive: $W_ON_SURFACE;
titleFg: $W_ON_SURFACE_VARIANT;
trayCounterBg: $W_PRIMARY;
trayCounterBgMute: $W_ON_SURFACE_FAINT;
trayCounterFg: $W_ON_PRIMARY;

// --- Boxes & overlays ---
layerBg: ${W_SHADOW}7f;
cancelIconFg: $W_ON_SURFACE_VARIANT;
cancelIconFgOver: $W_ON_SURFACE;
boxBg: $W_APP_BG;
boxTextFg: $W_ON_SURFACE;
boxTextFgGood: $W_TERM_ANSI_GREEN;
boxTextFgError: $W_DANGER;
boxTitleFg: $W_ON_SURFACE_BRIGHT;
boxSearchBg: $W_SURFACE_DIM;
boxTitleAdditionalFg: $W_ON_SURFACE_VARIANT;
boxTitleCloseFg: $W_ON_SURFACE_VARIANT;
boxTitleCloseFgOver: $W_ON_SURFACE;
membersAboutLimitFg: $W_DANGER;
toastBg: ${W_SURFACE_VARIANT}e5;
toastFg: $W_ON_SURFACE_BRIGHT;

// --- Contacts & intro ---
contactsBg: $W_APP_BG;
contactsBgOver: $W_SURFACE_DIM;
contactsNameFg: $W_ON_SURFACE_BRIGHT;
contactsStatusFg: $W_ON_SURFACE_VARIANT;
contactsStatusFgOver: $W_ON_SURFACE_VARIANT;
contactsStatusFgOnline: $W_ON_SURFACE_ACCENT;
photoCropFadeBg: ${W_SHADOW}7f;
photoCropPointFg: ${W_ON_SURFACE_BRIGHT}7f;
introBg: $W_APP_BG;
introTitleFg: $W_ON_SURFACE_BRIGHT;
introDescriptionFg: $W_ON_SURFACE_VARIANT;
introCoverTopBg: $W_PRIMARY;
introCoverBottomBg: $W_APP_BG;
introCoverIconsFg: $W_PRIMARY;
introCoverPlaneTrace: ${W_PRIMARY}69;
introCoverPlaneInner: $W_PRIMARY;
introCoverPlaneOuter: $W_APP_BG;
introCoverPlaneTop: $W_ON_PRIMARY;

// --- Chat list ---
dialogsMenuIconFg: $W_ON_SURFACE_VARIANT;
dialogsMenuIconFgOver: $W_ON_SURFACE_ACCENT;
dialogsBg: $W_APP_BG;
dialogsNameFg: $W_ON_SURFACE_BRIGHT;
dialogsChatIconFg: $W_ON_SURFACE;
dialogsDateFg: $W_ON_SURFACE_VARIANT;
dialogsTextFg: $W_ON_SURFACE_VARIANT;
dialogsTextFgService: $W_ON_SURFACE_ACCENT;
dialogsDraftFg: $W_DANGER;
dialogsVerifiedIconBg: $W_PRIMARY;
dialogsVerifiedIconFg: $W_ON_PRIMARY;
dialogsSendingIconFg: $W_ON_SURFACE_VARIANT;
dialogsSentIconFg: $W_ON_SURFACE_ACCENT;
dialogsUnreadBg: $W_PRIMARY;
dialogsUnreadBgMuted: $W_ON_SURFACE_FAINT;
dialogsUnreadFg: $W_ON_PRIMARY;
dialogsOnlineBadgeFg: $W_TERM_ANSI_GREEN;
dialogsMentionIconFg: $W_ON_SURFACE_ACCENT;
dialogsPollIconFg: $W_TERM_ANSI_BLUE;
dialogsReactionIconFg: $W_DANGER;
dialogsArchiveFg: $W_ON_SURFACE_FAINT;
dialogsArchiveFgOver: $W_ON_SURFACE_VARIANT;
dialogsBgOver: $W_SURFACE_DIM;
dialogsNameFgOver: $W_ON_SURFACE_BRIGHT;
dialogsChatIconFgOver: $W_ON_SURFACE;
dialogsDateFgOver: $W_ON_SURFACE;
dialogsTextFgOver: $W_ON_SURFACE;
dialogsTextFgServiceOver: $W_ON_SURFACE_ACCENT;
dialogsDraftFgOver: $W_DANGER;
dialogsVerifiedIconBgOver: $W_PRIMARY;
dialogsVerifiedIconFgOver: $W_ON_PRIMARY;
dialogsSendingIconFgOver: $W_ON_SURFACE;
dialogsSentIconFgOver: $W_ON_SURFACE_ACCENT;
dialogsUnreadBgOver: $W_PRIMARY;
dialogsUnreadBgMutedOver: $W_ON_SURFACE_FAINT;
dialogsUnreadFgOver: $W_ON_PRIMARY;
dialogsBgActive: $W_PRIMARY_CONTAINER;
dialogsNameFgActive: $W_ON_PRIMARY_CONTAINER;
dialogsChatIconFgActive: $W_ON_PRIMARY_CONTAINER;
dialogsDateFgActive: ${W_ON_PRIMARY_CONTAINER}cc;
dialogsTextFgActive: ${W_ON_PRIMARY_CONTAINER}e6;
dialogsTextFgServiceActive: $W_ON_PRIMARY_CONTAINER;
dialogsDraftFgActive: $W_ON_DANGER_CONTAINER;
dialogsVerifiedIconBgActive: $W_ON_PRIMARY_CONTAINER;
dialogsVerifiedIconFgActive: $W_PRIMARY_CONTAINER;
dialogsSendingIconFgActive: ${W_ON_PRIMARY_CONTAINER}99;
dialogsSentIconFgActive: $W_ON_PRIMARY_CONTAINER;
dialogsUnreadBgActive: $W_ON_PRIMARY_CONTAINER;
dialogsUnreadBgMutedActive: ${W_ON_PRIMARY_CONTAINER}99;
dialogsUnreadFgActive: $W_PRIMARY_CONTAINER;
dialogsOnlineBadgeFgActive: $W_ON_PRIMARY_CONTAINER;
searchedBarBg: $W_SURFACE_DIM;
searchedBarFg: $W_ON_SURFACE_VARIANT;
topBarBg: $W_APP_BG;
emojiPanBg: $W_APP_BG;
emojiPanCategories: $W_SURFACE_DIM;
emojiPanHeaderFg: $W_ON_SURFACE;
emojiPanHeaderBg: $W_SURFACE_DIM;
emojiIconFg: $W_ON_SURFACE_VARIANT;
emojiSubIconFgActive: $W_ON_SURFACE_ACCENT;

// --- Chat history ---
historyTextInFg: $W_ON_SURFACE_BRIGHT;
historyTextOutFg: $W_ON_PRIMARY_CONTAINER;
historyFileNameInFg: $W_ON_SURFACE_BRIGHT;
historyFileNameOutFg: $W_ON_PRIMARY_CONTAINER;
historyOutIconFg: $W_ON_PRIMARY_CONTAINER;
historyOutIconFgSelected: $W_ON_PRIMARY;
historyIconFgInverted: $W_ON_PRIMARY_CONTAINER;
historySendingOutIconFg: ${W_ON_PRIMARY_CONTAINER}aa;
historySendingInIconFg: $W_ON_SURFACE_VARIANT;
historySendingInvertedIconFg: ${W_ON_SURFACE_BRIGHT}c8;
historyUnreadBarBg: $W_SURFACE;
historyUnreadBarBorder: $W_SURFACE;
historyUnreadBarFg: $W_ON_SURFACE_ACCENT;
historyCallArrowInFg: $W_TERM_ANSI_GREEN;
historyCallArrowInFgSelected: $W_TERM_ANSI_BRIGHT_GREEN;
historyForwardChooseBg: ${W_SHADOW}4c;
historyToDownShadow: ${W_SHADOW}40;
mainMenuCloudBg: $W_PRIMARY;
rankAdminFg: $W_ON_SURFACE_ACCENT;
rankOwnerFg: $W_ON_SURFACE_VIVID;

// Peer colours (names + userpics in groups) — the ANSI hue wheel, the same
// roles the terminal and every editor in W use; Bg2 is the gradient's dark end.
historyPeer1NameFg: $W_TERM_ANSI_RED;
historyPeer1UserpicBg: $W_TERM_ANSI_BRIGHT_RED;
historyPeer1UserpicBg2: $W_TERM_ANSI_RED;
historyPeer2NameFg: $W_TERM_ANSI_GREEN;
historyPeer2UserpicBg: $W_TERM_ANSI_BRIGHT_GREEN;
historyPeer2UserpicBg2: $W_TERM_ANSI_GREEN;
historyPeer3NameFg: $W_TERM_ANSI_YELLOW;
historyPeer3UserpicBg: $W_TERM_ANSI_BRIGHT_YELLOW;
historyPeer3UserpicBg2: $W_TERM_ANSI_YELLOW;
historyPeer4NameFg: $W_TERM_ANSI_BLUE;
historyPeer4UserpicBg: $W_TERM_ANSI_BRIGHT_BLUE;
historyPeer4UserpicBg2: $W_TERM_ANSI_BLUE;
historyPeer5NameFg: $W_TERM_ANSI_MAGENTA;
historyPeer5UserpicBg: $W_TERM_ANSI_BRIGHT_MAGENTA;
historyPeer5UserpicBg2: $W_TERM_ANSI_MAGENTA;
historyPeer6NameFg: $W_TERM_ANSI_BRIGHT_RED;
historyPeer6UserpicBg: $W_TERM_ANSI_BRIGHT_MAGENTA;
historyPeer6UserpicBg2: $W_TERM_ANSI_RED;
historyPeer7NameFg: $W_TERM_ANSI_CYAN;
historyPeer7UserpicBg: $W_TERM_ANSI_BRIGHT_CYAN;
historyPeer7UserpicBg2: $W_TERM_ANSI_CYAN;
historyPeer8NameFg: $W_TERM_ANSI_BRIGHT_YELLOW;
historyPeer8UserpicBg: $W_TERM_ANSI_BRIGHT_YELLOW;
historyPeer8UserpicBg2: $W_TERM_ANSI_RED;
historyPeerUserpicFg: $W_ON_PRIMARY;

// Messages — incoming on the raised surface, outgoing on the W selection pair.
msgInBg: $W_SURFACE_VARIANT;
msgInBgSelected: $W_SURFACE_VARIANT;
msgOutBg: $W_PRIMARY_CONTAINER;
msgOutBgSelected: $W_PRIMARY;
msgSelectOverlay: ${W_PRIMARY}4c;
msgStickerOverlay: ${W_PRIMARY}7f;
msgInShadow: ${W_SHADOW}29;
msgInShadowSelected: ${W_SHADOW}29;
msgOutShadow: ${W_SHADOW}29;
msgOutShadowSelected: ${W_SHADOW}29;
msgInDateFg: $W_ON_SURFACE_VARIANT;
msgInDateFgSelected: $W_ON_SURFACE;
msgOutDateFg: ${W_ON_PRIMARY_CONTAINER}99;
msgOutDateFgSelected: $W_ON_PRIMARY;
msgServiceBg: ${W_SURFACE_VARIANT}b3;
msgServiceBgSelected: ${W_PRIMARY}a2;
msgServiceFg: $W_ON_SURFACE_BRIGHT;
msgInReplyBarColor: $W_PRIMARY;
msgOutReplyBarColor: $W_ON_PRIMARY_CONTAINER;
msgInMonoFg: $W_ON_SURFACE_ACCENT;
msgOutMonoFg: $W_ACCENT_ALT_SOFT;
msgOutServiceFg: $W_ON_PRIMARY_CONTAINER;
msgOutServiceFgSelected: $W_ON_PRIMARY;
msgDateImgBgSelected: ${W_PRIMARY_CONTAINER}87;

// Files & media — thumbnail hues on the ANSI wheel (1 blue, 2 green, 3 red,
// 4 yellow, as upstream); in/out file circles follow the bubble accents.
msgFileInBg: $W_PRIMARY;
msgFileInBgOver: $W_PRIMARY_CONTAINER;
msgFileInBgSelected: $W_PRIMARY_CONTAINER;
msgFileOutBg: $W_PRIMARY;
msgFileOutBgSelected: $W_PRIMARY_SOFT;
historyFileInRadialFg: $W_ON_PRIMARY;
historyFileOutRadialFg: $W_ON_PRIMARY;
msgFile1Bg: $W_TERM_ANSI_BLUE;
msgFile1BgDark: $W_TERM_ANSI_BLUE;
msgFile1BgOver: $W_TERM_ANSI_BRIGHT_BLUE;
msgFile1BgSelected: $W_TERM_ANSI_BRIGHT_BLUE;
msgFile2Bg: $W_TERM_ANSI_GREEN;
msgFile2BgDark: $W_TERM_ANSI_GREEN;
msgFile2BgOver: $W_TERM_ANSI_BRIGHT_GREEN;
msgFile2BgSelected: $W_TERM_ANSI_BRIGHT_GREEN;
msgFile3Bg: $W_TERM_ANSI_RED;
msgFile3BgDark: $W_TERM_ANSI_RED;
msgFile3BgOver: $W_TERM_ANSI_BRIGHT_RED;
msgFile3BgSelected: $W_TERM_ANSI_BRIGHT_RED;
msgFile4Bg: $W_TERM_ANSI_YELLOW;
msgFile4BgDark: $W_TERM_ANSI_YELLOW;
msgFile4BgOver: $W_TERM_ANSI_BRIGHT_YELLOW;
msgFile4BgSelected: $W_TERM_ANSI_BRIGHT_YELLOW;
msgFileThumbLinkOutFg: $W_ON_PRIMARY_CONTAINER;
msgFileThumbLinkOutFgSelected: $W_ON_PRIMARY;
msgWaveformInActive: $W_PRIMARY;
msgWaveformInInactive: $W_ON_SURFACE_FAINT;
msgWaveformInActiveSelected: $W_PRIMARY;
msgWaveformInInactiveSelected: $W_ON_SURFACE_VARIANT;
msgWaveformOutActive: $W_ON_PRIMARY_CONTAINER;
msgWaveformOutInactive: ${W_ON_PRIMARY_CONTAINER}80;
msgWaveformOutActiveSelected: $W_ON_PRIMARY;
msgWaveformOutInactiveSelected: ${W_ON_PRIMARY}80;

// --- Compose area ---
historyComposeAreaBg: $W_APP_BG;
historyComposeAreaFg: $W_ON_SURFACE_BRIGHT;
historyComposeIconFg: $W_ON_SURFACE_VARIANT;
historyComposeIconFgOver: $W_ON_SURFACE_ACCENT;
historySendIconFg: $W_PRIMARY;
historySendIconFgOver: $W_ON_SURFACE_VIVID;
historyReplyBg: $W_APP_BG;
historyReplyIconFg: $W_PRIMARY;
historyReplyCancelFg: $W_ON_SURFACE_VARIANT;

// --- Side bar (main menu / folders) ---
sideBarBg: $W_APP_BG;
sideBarBgActive: $W_SURFACE;
sideBarBgRipple: ${W_PRIMARY}33;
sideBarTextFgActive: $W_ON_SURFACE_ACCENT;
sideBarIconFgActive: $W_ON_SURFACE_ACCENT;
sideBarTextFg: $W_ON_SURFACE_VARIANT;
sideBarIconFg: $W_ON_SURFACE_VARIANT;
sideBarBadgeBg: $W_PRIMARY;
sideBarBadgeBgMuted: $W_ON_SURFACE_FAINT;
sideBarBadgeFg: $W_ON_PRIMARY;

// --- Media viewer ---
mediaviewBg: ${W_BG}eb;
mediaviewFileBg: $W_APP_BG;
mediaviewFileNameFg: $W_ON_SURFACE_BRIGHT;
mediaviewMenuBg: $W_SURFACE;
mediaviewMenuBgOver: $W_SURFACE_VARIANT;
mediaviewMenuBgRipple: ${W_PRIMARY}33;
mediaviewMenuFg: $W_ON_SURFACE_BRIGHT;
mediaviewPlaybackActive: $W_PRIMARY;
mediaviewPlaybackInactive: $W_SURFACE_VARIANT;
mediaviewTextLinkFg: $W_ON_SURFACE_ACCENT;
mediaviewFileBlueCornerFg: $W_TERM_ANSI_BLUE;
mediaviewFileGreenCornerFg: $W_TERM_ANSI_GREEN;
mediaviewFileRedCornerFg: $W_TERM_ANSI_RED;
mediaviewFileYellowCornerFg: $W_TERM_ANSI_YELLOW;
EOF
)

  # Sentinel first: under `set -u` a typo'd token name kills the command
  # substitution INSIDE its subshell, the assignment survives empty, and an
  # empty palette would ship inside a valid-looking archive and silently replace
  # the applied colours with tdesktop's defaults.
  if [[ -z "$palette" || ! "$palette" == *"windowBg:"* ]]; then
    echo "w-style: telegram — rendered palette is empty/malformed (token typo?), refusing to write." >&2
    return 1
  fi

  # Assemble the ZIP theme: palette text + a flat 64×64 tile in the chat
  # wallpaper colour. W_SURFACE_DIM sits one step above the window background
  # (W_APP_BG) that the chat list, top bar and compose area use, so the chat
  # canvas reads as its own surface while incoming bubbles (W_SURFACE_VARIANT)
  # and the outgoing pair still stand out on it.
  require_magick
  local work; work="$(mktemp -d)" || { echo "w-style: telegram — mktemp failed." >&2; return 1; }
  printf '%s\n' "$palette" >"$work/colors.tdesktop-theme"
  if ! magick -size 64x64 "xc:$W_SURFACE_DIM" "PNG24:$work/tiled.png" 2>/dev/null \
     || ! bsdtar --format zip -cf "$work/w.zip" -C "$work" colors.tdesktop-theme tiled.png; then
    echo "w-style: telegram — could not build the theme archive (magick/bsdtar), refusing to write." >&2
    rm -rf "$work"; return 1
  fi

  # In-place write (same inode): tdesktop's live reload is a QFileSystemWatcher
  # on this path — rename would swap the inode out from under it.
  _tg_write_binary "$TELEGRAM_THEME_REL" "$work/w.zip"
  rm -rf "$work"

  if [[ $EUID -eq 0 ]]; then
    echo "w-style: telegram done (skel template; accounts apply it once from Chat settings)."
  else
    echo "w-style: telegram done (live in a Telegram that uses the file; see w-pack setup telegram)."
  fi
}
