# w-style module: lazygit (user-scope) — git TUI theme.
#
# Ships INSIDE the dev W-Pack (source of truth); `w-pack install dev` drops this
# axis into the w-style modules.d drop-in root and renders it. Core w-style carries
# no reference to lazygit → the axis exists iff the bundle is installed, so no
# presence-guard is needed (packs.md "bundle self-containment", pack-dev.md).
#
# OWNERSHIP SPLIT — unlike the lazydocker axis (which owns the whole config.yml
# because lazydocker has no layering), lazygit natively merges a comma-separated
# list of config files, last one winning. So the split is clean:
#   ~/.config/lazygit/config.yml  the USER's (bundle manifest, behaviour only)
#   ~/.config/w/lazygit-theme.yml W's, rendered here, NOT in the manifest
# /etc/w/env.d/dev.sh sets LG_CONFIG_FILE to "user,theme" — see pack-dev.md.
#
# NOT live (lazygit reads its config at startup) and, because the merge rides the
# session env, only active from the next login after the bundle is installed.
# Band 500 = terminal/CLI.
#
# No new theme tokens: lazygit's palette is small and maps straight onto Tier-2
# roles + the Tier-3 terminal pigments, same as the lazydocker/btop axes.
DESC="lazygit TUI theme"

LAZYGIT_THEME_REL=".config/w/lazygit-theme.yml"

render_user() {
  load_conf "$(w_userscope_theme_dir)"
  echo "w-style: rendering lazygit theme..."

  # YAML: brand colours start with '#', so each must be single-quoted or YAML reads
  # it as a comment. Every theme value is a LIST of strings (colour and/or attribute).
  write_user_file "$LAZYGIT_THEME_REL" <<EOF
# W Linux — generated by w-style. Do not edit; edit the theme's theme.conf.
# Merged over ~/.config/lazygit/config.yml via LG_CONFIG_FILE (/etc/w/env.d/dev.sh).
# Colours only — behaviour belongs in your own config.yml.
gui:
  theme:
    activeBorderColor:
      - '$W_PRIMARY'
      - bold
    inactiveBorderColor:
      - '$W_ON_SURFACE_VARIANT'
    searchingActiveBorderColor:
      - '$W_TERM_ANSI_YELLOW'
      - bold
    optionsTextColor:
      - '$W_ON_SURFACE_VARIANT'
    selectedLineBgColor:
      - '$W_PRIMARY_CONTAINER'
    inactiveViewSelectedLineBgColor:
      - '$W_SURFACE_VARIANT'
    cherryPickedCommitFgColor:
      - '$W_ON_PRIMARY_CONTAINER'
    cherryPickedCommitBgColor:
      - '$W_PRIMARY_CONTAINER'
    markedBaseCommitFgColor:
      - '$W_ON_DANGER_CONTAINER'
    markedBaseCommitBgColor:
      - '$W_DANGER_CONTAINER'
    unstagedChangesColor:
      - '$W_TERM_ANSI_RED'
    defaultFgColor:
      - '$W_ON_SURFACE'
EOF

  echo "w-style: lazygit done (applies to the next lazygit invocation)."
}
