#!/usr/bin/env bash
# Hyprland wiki -> skill navigator (W AI knowledge layer).
# Updates the local hyprland-wiki checkout and regenerates MAP.md
# (page tree + section table of contents built from every _index.md).
#
# On a W machine this is invoked by the W AI module (apply.sh --ai): once at
# deploy time to seed the checkout, then periodically by a system timer to keep
# it fresh. It is not meant to be run by the assistant. Requires: git, tree.
#
# Idempotent and offline-tolerant: if the network is down it keeps the existing
# checkout and still regenerates MAP.md. Runs relative to this script, so it
# works regardless of where the skill tree is installed.

set -euo pipefail

# Run relative to this script, regardless of caller's cwd.
cd "$(dirname "$(readlink -f "$0")")"

REPO_URL="https://github.com/hyprwm/hyprland-wiki.git"
WIKI_DIR="hyprland-wiki"
CONTENT_DIR="$WIKI_DIR/content"
MAP_FILE="MAP.md"

# --- deps -------------------------------------------------------------------
for dep in git tree; do
  command -v "$dep" >/dev/null 2>&1 || { echo "error: '$dep' is required" >&2; exit 1; }
done

# --- update checkout --------------------------------------------------------
if [ -d "$WIKI_DIR/.git" ]; then
  echo ":: Updating hyprland-wiki..."
  if ! git -C "$WIKI_DIR" pull --ff-only; then
    echo ":: warning: update failed (offline?). Using existing checkout." >&2
  fi
else
  echo ":: Cloning hyprland-wiki (shallow)..."
  git clone --depth 1 --single-branch "$REPO_URL" "$WIKI_DIR"
fi

[ -d "$CONTENT_DIR" ] || { echo "error: '$CONTENT_DIR' not found" >&2; exit 1; }

# --- extraction helpers -----------------------------------------------------
# Title from YAML frontmatter `title:`; empty if absent.
extract_title() {
  awk '
    NR==1 && /^---[[:space:]]*$/ { fm=1; next }
    fm==1 && /^---[[:space:]]*$/ { exit }
    fm==1 && /^title:[[:space:]]*/ {
      sub(/^title:[[:space:]]*/, ""); gsub(/^["'\'']|["'\'']$/, ""); print; exit
    }
  ' "$1"
}

# First prose line after optional frontmatter: skip blanks, markdown headings
# and blockquote/note markers; fall back to first heading text. Empty if none.
extract_summary() {
  awk '
    NR==1 && /^---[[:space:]]*$/ { fm=1; next }
    fm==1 { if (/^---[[:space:]]*$/) fm=2; next }
    /^[[:space:]]*$/ { next }
    /^```/ { fence = !fence; next }
    fence { next }
    { s=$0; sub(/^[[:space:]]+/, "", s); sub(/[[:space:]]+$/, "", s) }
    s ~ /^#/ { if (h=="") { h=s; sub(/^#+[[:space:]]*/, "", h) } next }
    s ~ /^>/ { next }
    { print s; found=1; exit }
    END { if (!found && h!="") print h }
  ' "$1"
}

# --- generate MAP.md --------------------------------------------------------
echo ":: Regenerating $MAP_FILE..."
tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

{
  echo "# Hyprland Wiki — Navigation Map"
  echo
  echo "> Auto-generated by \`install.sh\`. Do not edit by hand."
  echo "> Wiki revision: $(git -C "$WIKI_DIR" rev-parse --short HEAD 2>/dev/null || echo unknown)"
  echo "> Generated: $(date -u '+%Y-%m-%d %H:%M UTC')"
  echo
  echo "Paths below are relative to \`$CONTENT_DIR/\`."
  echo
  echo "## Page tree"
  echo
  echo '```'
  tree -h --noreport "$CONTENT_DIR"
  echo '```'
  echo
  echo "## Annotated index"
  echo
  echo "Every section and page with a one-line summary, in wiki order."
  echo "Per section: the section summary (from \`_index.md\`), then its pages."
  echo

  # Walk directories top-down (parent before children) so each section's
  # summary precedes its pages.
  find "$CONTENT_DIR" -type d | sort | while read -r dir; do
    rel="${dir#"$CONTENT_DIR"}"
    rel="${rel#/}"
    [ -n "$rel" ] && label="$rel" || label="(root)"

    echo "### $label/"
    idx="$dir/_index.md"
    pages="$(find "$dir" -maxdepth 1 -type f -name '*.md' ! -name '_index.md' | sort)"

    if [ -f "$idx" ]; then
      s="$(extract_summary "$idx")"
      if [ -z "$pages" ]; then
        # Leaf section: _index.md is the content itself -> render as a page.
        title="$(extract_title "$idx")"; [ -n "$title" ] || title="$label"
        [ -n "$s" ] && echo "- **$title** (\`_index.md\`) — $s" \
                    || echo "- **$title** (\`_index.md\`)"
      else
        # Section with pages: _index.md is an intro -> show as summary.
        [ -n "$s" ] && echo "$s" && echo
      fi
    fi

    # Pages in this directory (exclude _index.md), each with title + summary.
    printf '%s\n' "$pages" | while read -r page; do
      [ -n "$page" ] || continue
      base="$(basename "$page")"
      title="$(extract_title "$page")"
      [ -n "$title" ] || title="${base%.md}"
      psum="$(extract_summary "$page")"
      if [ -n "$psum" ]; then
        echo "- **$title** (\`$base\`) — $psum"
      else
        echo "- **$title** (\`$base\`)"
      fi
    done
    echo
  done
} >"$tmp"

mv "$tmp" "$MAP_FILE"
# mktemp creates the temp file 0600; the assistant reads MAP.md as the ordinary
# user, so make it world-readable like the rest of the shipped knowledge tree.
chmod 0644 "$MAP_FILE"
trap - EXIT

echo ":: Done. $MAP_FILE updated ($(wc -l <"$MAP_FILE") lines)."
