# w-style module: yazi (user-scope) — CLI file-manager palette.
# Partial theme (yazi merges over its built-in), incl. the [filetype] rule
# url = "*/" (directories) = W_YAZI_FILE_DIR (= W_DIR_HUE, shared CLI dir tone).
# NOT live: read at startup → new instances. Band 500 = terminal/CLI.
DESC="yazi file-manager palette (TUI)"

YAZI_THEME_REL=".config/yazi/theme.toml"

render_user() {
  load_conf "$(w_userscope_theme_dir)"
  echo "w-style: rendering yazi theme..."

  write_user_file "$YAZI_THEME_REL" <<EOF
# W Linux — generated by w-style. Do not edit; edit the theme's theme.conf.
[mgr]
cwd             = { fg = "$W_YAZI_CWD" }
hovered         = { fg = "$W_YAZI_HOVERED_FG", bg = "$W_YAZI_HOVERED_BG" }
preview_hovered = { underline = true }
find_keyword    = { fg = "$W_YAZI_FIND", bold = true }
find_position   = { fg = "$W_YAZI_FIND", bg = "reset", bold = true }
marker_selected = { fg = "$W_YAZI_MARKER_SELECTED", bg = "$W_YAZI_MARKER_SELECTED" }
marker_copied   = { fg = "$W_YAZI_MARKER_COPIED", bg = "$W_YAZI_MARKER_COPIED" }
marker_cut      = { fg = "$W_YAZI_MARKER_CUT", bg = "$W_YAZI_MARKER_CUT" }
border_symbol   = "│"
border_style    = { fg = "$W_YAZI_BORDER" }

[mode]
normal_main = { fg = "$W_YAZI_MODE_NORMAL_FG", bg = "$W_YAZI_MODE_NORMAL_BG", bold = true }
normal_alt  = { fg = "$W_YAZI_MODE_NORMAL_BG", bg = "$W_YAZI_MODE_NORMAL_FG" }
select_main = { fg = "$W_YAZI_MODE_SELECT_FG", bg = "$W_YAZI_MODE_SELECT_BG", bold = true }
select_alt  = { fg = "$W_YAZI_MODE_SELECT_BG", bg = "$W_YAZI_MODE_SELECT_FG" }
unset_main  = { fg = "$W_YAZI_MODE_UNSET_FG", bg = "$W_YAZI_MODE_UNSET_BG", bold = true }
unset_alt   = { fg = "$W_YAZI_MODE_UNSET_BG", bg = "$W_YAZI_MODE_UNSET_FG" }

[input]
border   = { fg = "$W_YAZI_BORDER" }
selected = { reversed = true }

[pick]
border = { fg = "$W_YAZI_BORDER" }
active = { fg = "$W_YAZI_MODE_NORMAL_BG", bold = true }

[confirm]
border = { fg = "$W_YAZI_BORDER" }

[tasks]
border = { fg = "$W_YAZI_BORDER" }

[which]
separator_style = { fg = "$W_YAZI_BORDER" }

[filetype]
# Directories in the shared terminal "dir hue" (W_DIR_HUE) — the same tone
# LS_COLORS \`di\` and the shell path segment use, so dirs read alike across the
# CLI. yazi matches directories by the trailing-slash glob on \`url\` ("*/").
# (A rule needs \`url\` or \`mime\`; \`is\` only accepts fs node types, not "dir".)
# Rest stays default.
rules = [
  { url = "*/", fg = "$W_YAZI_FILE_DIR" },
]
EOF

  echo "w-style: yazi done (applies to newly launched yazi instances)."
}
