# w-style module: foot (user-scope) — fallback terminal palette + bg translucency.
# Mirrors the ghostty axis: the static foot.ini (user seed) includes the generated
# file this module writes. Translucency comes from the effects axis (W_FX_TERM_OPACITY,
# shared with ghostty) — bg only, text opaque; the compositor blurs behind. Band 500 =
# terminal/CLI.
#
# NOT live: foot has no config-reload signal. Its only signals are SIGUSR1/SIGUSR2,
# which switch between the [colors-dark]/[colors-light] themes ALREADY loaded in
# memory — they do not re-read the file. So a theme change lands on the next foot
# launch (acceptable for a fallback terminal; Ghostty is the live primary surface).
# We always render the active W palette into [colors-dark] (foot's default theme,
# orthogonal to W's own dark/light appearance axis).
DESC="foot terminal palette + bg opacity (applies on next launch)"

FOOT_THEME_REL=".config/foot/themes/w"

# Foot wants colours as RRGGBB (no leading '#'); theme tokens carry '#RRGGBB'.
hx() { local v="$1"; echo "${v#\#}"; }

render_user() {
  local theme_dir; theme_dir="$(w_userscope_theme_dir)"
  load_conf "$theme_dir"
  load_effects "$(resolve_theme_file "$theme_dir" effects.conf)"
  echo "w-style: rendering foot theme..."

  write_user_file "$FOOT_THEME_REL" <<EOF
# W Linux — generated by w-style. Do not edit; edit the theme's theme.conf / effects.conf.
[colors-dark]
alpha=$W_FX_TERM_OPACITY
background=$(hx "$W_TERM_BG")
foreground=$(hx "$W_TERM_FG")
cursor=$(hx "$W_TERM_CURSOR_TEXT") $(hx "$W_TERM_CURSOR")
selection-foreground=$(hx "$W_TERM_SELECTION_FG")
selection-background=$(hx "$W_TERM_SELECTION_BG")

regular0=$(hx "$W_TERM_ANSI_BLACK")
regular1=$(hx "$W_TERM_ANSI_RED")
regular2=$(hx "$W_TERM_ANSI_GREEN")
regular3=$(hx "$W_TERM_ANSI_YELLOW")
regular4=$(hx "$W_TERM_ANSI_BLUE")
regular5=$(hx "$W_TERM_ANSI_MAGENTA")
regular6=$(hx "$W_TERM_ANSI_CYAN")
regular7=$(hx "$W_TERM_ANSI_WHITE")

bright0=$(hx "$W_TERM_ANSI_BRIGHT_BLACK")
bright1=$(hx "$W_TERM_ANSI_BRIGHT_RED")
bright2=$(hx "$W_TERM_ANSI_BRIGHT_GREEN")
bright3=$(hx "$W_TERM_ANSI_BRIGHT_YELLOW")
bright4=$(hx "$W_TERM_ANSI_BRIGHT_BLUE")
bright5=$(hx "$W_TERM_ANSI_BRIGHT_MAGENTA")
bright6=$(hx "$W_TERM_ANSI_BRIGHT_CYAN")
bright7=$(hx "$W_TERM_ANSI_BRIGHT_WHITE")
EOF

  echo "w-style: foot done."
}
