# W Linux — zsh interactive shell config.
# Theme colors live in ~/.config/w/shell-colors.zsh (generated by w-style from the
# active theme). This file is behaviour only; do not hardcode colors here.

# ── History ───────────────────────────────────────────────────────────────────
HISTFILE="$HOME/.zsh_history"
HISTSIZE=10000
SAVEHIST=10000
setopt HIST_IGNORE_DUPS HIST_IGNORE_SPACE SHARE_HISTORY INC_APPEND_HISTORY

# ── Shell behaviour ─────────────────────────────────────────────────────────────
setopt AUTO_CD INTERACTIVE_COMMENTS
autoload -Uz compinit && compinit -d "$HOME/.cache/zcompdump"
zstyle ':completion:*' menu select
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'

# ── W theme colors (LS_COLORS / fzf / zsh-* highlight styles) ───────────────────
# Generated by w-style (truecolor, exact theme hex). Sourced now, and re-sourced
# live whenever it changes (a `w-theme set` rewrites it) so OPEN terminals recolor
# without a new shell. zsh/stat gives the mtime; the precmd hook is near-free.
_w_shell_colors="$HOME/.config/w/shell-colors.zsh"
[[ -r "$_w_shell_colors" ]] && source "$_w_shell_colors"
zmodload -F zsh/stat b:zstat 2>/dev/null
typeset -g _w_shell_colors_mtime=0
_w_reload_shell_colors() {
  [[ -r "$_w_shell_colors" ]] || return
  local m; m="$(zstat +mtime "$_w_shell_colors" 2>/dev/null)" || return
  [[ "$m" == "$_w_shell_colors_mtime" ]] && return
  _w_shell_colors_mtime="$m"
  source "$_w_shell_colors"
}
autoload -Uz add-zsh-hook
add-zsh-hook precmd _w_reload_shell_colors

# ── Aliases ─────────────────────────────────────────────────────────────────────
# Modern CLI first (eza/bat), with a graceful fallback to coreutils. eza icons +
# colors and bat highlighting follow the active theme (EZA_COLORS via w-style; bat
# rides the ghostty palette through BAT_THEME=ansi).
if command -v eza &>/dev/null; then
  alias ls='eza --group-directories-first --icons=auto'
  alias ll='eza -lh --group-directories-first --icons=auto --git'
  alias la='eza -lah --group-directories-first --icons=auto --git'
  alias lt='eza --tree --level=2 --group-directories-first --icons=auto'
else
  alias ls='ls --color=auto --group-directories-first'
  alias ll='ls -lh'
  alias la='ls -lAh'
fi
if command -v bat &>/dev/null; then
  alias cat='bat -pp'
  export BAT_THEME=ansi
fi
alias grep='grep --color=auto'

# ── Tools ───────────────────────────────────────────────────────────────────────
command -v starship &>/dev/null && eval "$(starship init zsh)"
command -v zoxide   &>/dev/null && eval "$(zoxide init zsh)"
[[ -r /usr/share/fzf/key-bindings.zsh ]] && source /usr/share/fzf/key-bindings.zsh
[[ -r /usr/share/fzf/completion.zsh   ]] && source /usr/share/fzf/completion.zsh
# atuin owns history search (Ctrl+R + ↑); init AFTER fzf so it wins those binds.
command -v atuin &>/dev/null && eval "$(atuin init zsh)"

# ── Interactive-shell drop-in root for optional W-Packs bundles ────────────────
# Mirror of /etc/w/env.d (session env, sourced by env-hyprland): a bundle that needs
# to hook the INTERACTIVE shell — something env vars cannot express, e.g. mise's
# per-prompt PATH activation — ships a managed /etc/w/zshrc.d/<bundle>.zsh via its
# manifest. Removing the bundle removes the file. Core carries no per-bundle shell
# code; no-op when no bundle is installed. See packs.md.
#
# Position is part of the contract: AFTER the tool inits above (a drop-in may rely
# on add-zsh-hook and on PATH already carrying ~/.local/bin) and BEFORE the
# completion/plugin blocks below, whose load order is fixed and must stay last.
if [[ -d /etc/w/zshrc.d ]]; then
  for _wzrc in /etc/w/zshrc.d/*.zsh(N); do
    [[ -r "$_wzrc" ]] && source "$_wzrc"
  done
  unset _wzrc
fi

# ── Completion UX (fzf-tab: fuzzy completion menu) ──────────────────────────────
# Load after compinit and BEFORE the widget-wrapping plugins below (plugin order
# requirement). Inherits the theme's FZF colors via FZF_DEFAULT_OPTS.
if [[ -r /usr/share/zsh/plugins/fzf-tab/fzf-tab.plugin.zsh ]]; then
  source /usr/share/zsh/plugins/fzf-tab/fzf-tab.plugin.zsh
  zstyle ':completion:*' menu no                        # let fzf-tab take over
  zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"
  zstyle ':fzf-tab:*' use-fzf-default-opts yes          # inherit the W FZF colors
  zstyle ':fzf-tab:*' switch-group ',' '.'
fi

# ── Plugins (autosuggestions first; syntax-highlighting MUST be sourced last) ───
[[ -r /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh ]] \
  && source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
[[ -r /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ]] \
  && source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
