# w-style module: hyprland (user-scope) — window border + background colors.
# Contract: DESC + render_user()/render_system(). Sourced by the orchestrator into
# an isolated subshell with core.sh already loaded. Band 100 = compositor surfaces.
DESC="Hyprland window borders + background"

# Lua data module require()d by hyprland.lua (returns a table of colors, threaded
# into hl.config general.col.* and misc.background_color). Since 0.55 Hyprland's
# config is Lua; the compositor's own config no longer uses hyprlang $-variables.
HYPR_COLORS_REL=".config/hypr/colors.lua"

render_user() {
  load_conf "$(w_userscope_theme_dir)"
  echo "w-style: rendering Hyprland colors..."

  write_user_file "$HYPR_COLORS_REL" <<EOF
-- W Linux — generated by w-style. Do not edit; edit the theme's theme.conf instead.
-- require()d by hyprland.lua; values go into general.col.* + misc.background_color
-- and the group{}/groupbar{} block (tab pills).
return {
  border_active = "$(hypr_rgba "$W_HYPR_BORDER_ACTIVE")",
  border_inactive = "$(hypr_rgba "$W_HYPR_BORDER_INACTIVE")",
  bg = "$(hypr_rgba "$W_HYPR_BG")",
  group_border_active = "$(hypr_rgba "$W_HYPR_GROUP_BORDER_ACTIVE")",
  group_border_inactive = "$(hypr_rgba "$W_HYPR_GROUP_BORDER_INACTIVE")",
  tab_active_bg = "$(hypr_rgba "$W_HYPR_TAB_ACTIVE_BG")",
  tab_inactive_bg = "$(hypr_rgba "$W_HYPR_TAB_INACTIVE_BG")",
  tab_active_fg = "$(hypr_rgba "$W_HYPR_TAB_ACTIVE_FG")",
  tab_inactive_fg = "$(hypr_rgba "$W_HYPR_TAB_INACTIVE_FG")",
}
EOF

  hypr_reload
  echo "w-style: Hyprland done."
}
