# w-style module: tmux (user-scope) — status/pane colors (Tier-2 roles).
# tmux.conf (skel) sources this file; a running server picks it up on
# `tmux source ~/.tmux.conf` or reload. Band 500 = terminal/CLI.
DESC="tmux status/pane colors"

TMUX_COLORS_REL=".config/tmux/w-colors.conf"

render_user() {
  load_conf "$(w_userscope_theme_dir)"
  echo "w-style: rendering tmux colors..."

  write_user_file "$TMUX_COLORS_REL" <<EOF
# W Linux — generated by w-style. Do not edit; edit the theme's theme.conf.
set -g status-style "bg=$W_SURFACE_DIM,fg=$W_ON_SURFACE"
set -g status-left-style "fg=$W_ON_PRIMARY,bg=$W_PRIMARY,bold"
set -g status-right-style "fg=$W_ON_SURFACE_VARIANT"
set -g window-status-current-style "fg=$W_ON_PRIMARY_CONTAINER,bg=$W_PRIMARY_CONTAINER,bold"
set -g window-status-style "fg=$W_ON_SURFACE_VARIANT"
set -g window-status-activity-style "fg=$W_PRIMARY"
set -g pane-border-style "fg=$W_SURFACE_VARIANT"
set -g pane-active-border-style "fg=$W_PRIMARY"
set -g message-style "fg=$W_ON_SURFACE,bg=$W_SURFACE_VARIANT"
set -g message-command-style "fg=$W_ON_SURFACE,bg=$W_SURFACE_VARIANT"
set -g mode-style "fg=$W_ON_PRIMARY_CONTAINER,bg=$W_PRIMARY_CONTAINER"
set -g clock-mode-colour "$W_PRIMARY"
set -g copy-mode-match-style "fg=$W_ON_SURFACE,bg=$W_SURFACE_VARIANT"
set -g copy-mode-current-match-style "fg=$W_ON_PRIMARY_CONTAINER,bg=$W_PRIMARY"
EOF

  echo "w-style: tmux done (reload a running server: tmux source ~/.tmux.conf)."
}
